logging.file.name=kb-module.log
logging.pattern.console=%clr(%d{${LOG_DATEFORMAT_PATTERN:-yyyy-MM-dd HH:mm:ss.SSS}}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr( %X{requestID}:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}
logging.pattern.file=%d{${LOG_DATEFORMAT_PATTERN:-yyyy-MM-dd HH:mm:ss.SSS}} ${LOG_LEVEL_PATTERN:-%5p} ${PID:- } --- [%t] %-40.40logger{39} %X{requestID}: %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}

pam.url = http://localhost:8083/attestation
nsi.url.dict =http://localhost:8082

kafka.ack.nack.sleep-time = 3000

#kafka ssl properties
kafka.sslTruststorePassword=
kafka.sslKeystorePassword=
kafka.client.truststore-path=
kafka.client.keystore-path=

kafka.ccm.is-prod=false
kafka.ccm.bootstrap-servers = localhost:9092
kafka.ccm.consumer.group-id = service-prod.app-apcs.kb.attest-request
kafka.ccm.topicReq = 000-1.l3-ccm-pgp.db.Attestation-Request.0
kafka.ccm.schema.registry.url=

kafka.pdm.schema.registry.url=
kafka.pdm.bootstrap-servers = localhost:9092
kafka.pdm.consumer.group-id = service-prod.app-apcs.pdm
kafka.pdm.topic.microstructure = 000-0.l3-pdm.cdc.sp-microstructure.0
kafka.pdm.topic.asap-chemical-properties = 000-0.l3-pdm.cdc.sp-asap-chemical-properties.0
kafka.pdm.topic.equivalents=000-0.l3-pdm.cdc.sp-equivalents.0
kafka.pdm.topic.match-tk-num=000-0.l3-pdm.cdc.sp-match-tk-num.0
kafka.pdm.topic.match-rabplan-num=000-0.l3-pdm.cdc.sp-match-rabplan-num.0
kafka.pdm.topic.pcm=000-0.l3-pdm.cdc.sp-pcm.0
kafka.pdm.topic.asap-tol-links=000-0.l3-pdm.cdc.sp-asap-tol-links.0
kafka.pdm.topic.kat-steel-4041=000-0.l3-pdm.cdc.sp-kat-steel-mark-gost4041.0
kafka.pdm.topic.tol-thick=000-0.l3-pdm.cdc.sp-tol-thick.0
kafka.pdm.topic.tol-width=000-0.l3-pdm.cdc.sp-tol-width.0
kafka.pdm.topic.tol-length=000-0.l3-pdm.cdc.sp-tol-length.0
kafka.pdm.topic.asap-mech-properties=000-0.l3-pdm.cdc.asap-mech-properties.0
kafka.pdm.topic.tol-evenness=000-0.l3-pdm.cdc.sp-tol-evenness.0
kafka.pdm.topic.tk-num=000-0.l3-pdm.cdc.sp-tk-num.0
kafka.pdm.topic.ceq=000-0.l3-pdm.cdc.sp-ceq.0
kafka.pdm.topic.mech-properties=000-0.l3-pdm.cdc.sp-mech-properties.0
kafka.pdm.topic.chemical-properties=000-0.l3-pdm.cdc.sp-chemical-properties.0

kafka.sadim.bootstrap-servers=localhost:9092
kafka.sadim.group-id = service-prod.app-apcs.sadim
kafka.sadim.topic = PA-MU.NLMK.P3.HSM

#spring.jpa.properties.javax.persistence.schema-generation.scripts.action=create
#spring.jpa.properties.javax.persistence.schema-generation.scripts.create-target=schema.sql

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.disable-swagger-default-url=true