pam.url = http://localhost:8083/attestation
nsi.url.dict =http://localhost:8082/nsi

kafka.schema.registry.url =

kafka.sup.bootstrap-servers = localhost:9092
kafka.sup.consumer.group-id = service-prod.app-apcs.kb
kafka.sup.topicIp = 000-1.l3-sup.db.nlmk.integral-parameters.0
kafka.sup.topicUp = 000-1.l3-sup.db.nlmk.unrecoverable-parameters-trends.0

kafka.ccm.bootstrap-servers = localhost:9092
kafka.ccm.consumer.group-id = service-prod.app-apcs.kb.attest-request
kafka.ccm.topicReq = 000-1.l3-ccm-pgp.db.Attestation-Request.0

kafka.pdm.bootstrap-servers = localhost:9092
kafka.pdm.consumer.group-id = service-prod.app-apcs.pdm
kafka.pdm.topic.microstructure = 000-1.l3-pdm.cdc.sp-microstructure.0
kafka.pdm.topic.asap-chemical-properties = 000-1.l3-pdm.cdc.sp-asap-chemical-properties.0
kafka.pdm.topic.equivalents=000-1.l3-pdm.cdc.sp-equivalents.0

#spring.jpa.properties.javax.persistence.schema-generation.scripts.action=create
#spring.jpa.properties.javax.persistence.schema-generation.scripts.create-target=schema.sql