kafka.sup.bootstrap-servers = localhost:9092
kafka.sup.consumer.group-id = service-prod.app-apcs.kb
kafka.sup.topicIp = 000-1.l3-sup.db.nlmk.integral-parameters.0
kafka.sup.topicUp = 000-1.l3-sup.db.nlmk.unrecoverable-parameters-trends.0
kafka.schema.registry.url =

#spring.jpa.properties.javax.persistence.schema-generation.scripts.action=create
#spring.jpa.properties.javax.persistence.schema-generation.scripts.create-target=schema.sql

kafka.ccm.bootstrap-servers = localhost:9092
kafka.ccm.consumer.group-id = service-prod.app-apcs.kb.attest-request
kafka.ccm.topicReq = 000-1.l3-ccm-pgp.db.Attestation-Request.0

pam.url = http://localhost:8083/attestation