spring.application.name=kb-server
server.port=8089

spring.jackson.deserialization.fail_on_unknown_properties=false

logging.file.name=kb-module.log
logging.pattern.console=%clr(%d{${LOG_DATEFORMAT_PATTERN:-yyyy-MM-dd HH:mm:ss.SSS}}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr( %X{requestID}:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}
logging.pattern.file=%d{${LOG_DATEFORMAT_PATTERN:-yyyy-MM-dd HH:mm:ss.SSS}} ${LOG_LEVEL_PATTERN:-%5p} ${PID:- } --- [%t] %-40.40logger{39} %X{requestID}: %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}

opentracing.jaeger.log-spans=false
opentracing.jaeger.udp-sender.host=${JAEGER_HOST}
opentracing.jaeger.udp-sender.port=${JAEGER_PORT}

springdoc.swagger-ui.oauth.use-pkce-with-authorization-code-grant=true
springdoc.swagger-ui.oauth.client-id=${SSO_RESOURCE}
springdoc.use-fqn=true

management.endpoints.web.exposure.include=health,info,metrics,prometheus,shutdown
management.metrics.web.server.request.autotime.enabled=false
management.endpoint.health.show-details=always
#ALLOW shutdown application (need ADD and ALLOW!)
management.endpoint.shutdown.enabled=true
#k8s probes
management.endpoint.health.probes.enabled=true
server.shutdown=graceful
#less then k8s terminationGracePeriodSeconds (30sec)
spring.lifecycle.timeout-per-shutdown-phase=20s

spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.generate-ddl=false
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

spring.flyway.enabled=true
#need user profile dev or prod for FULL filling database!
spring.flyway.locations=classpath:db/migration

service-web-client.timeout=20000
service-web-client.nsi-server.url=${NSI_SERVER_BASEURL}
service-web-client.pam-server.url=${PAM_SERVER_BASEURL}
service-web-client.psm-server.url=${PSM_SERVER_BASEURL}
service-web-client.kafka-rest.address=${KAFKA_REST_ADDRESS}
service-web-client.kafka-rest.login=${KAFKA_REST_LOGIN}
service-web-client.kafka-rest.password=${KAFKA_REST_PASSWORD}

#value 'keycloak' set in WebClientConfig.CLIENT_REGISTRATION_ID
spring.security.oauth2.client.provider.keycloak.token-uri=${SSO_URL}/realms/${SSO_REALM}/protocol/openid-connect/token
spring.security.oauth2.client.registration.keycloak.authorization-grant-type=client_credentials
spring.security.oauth2.client.registration.keycloak.clientId=${SSO_CLIENT}
spring.security.oauth2.client.registration.keycloak.clientSecret=${SSO_CLIENT_SECRET}

keycloak.authServerUrl=${SSO_URL}
keycloak.realm=${SSO_REALM}
keycloak.resource=${SSO_RESOURCE}
keycloak.bearer-only=true

#KAFKA
kafka.ack.nack.sleep-time=5000
kafka.sslTruststorePassword=${KAFKA_TRUSTSTORE_PASSWORD}
kafka.sslKeystorePassword=${KAFKA_KEYSTORE_PASSWORD}
kafka.client.truststore-path=/etc/secret-volume/client.truststore.jks
kafka.client.keystore-path=/etc/secret-volume/client.keystore.jks

#ccm PGP
kafka.ccm.pgp.ssl-enabled=${KAFKA_CCM_PGP_SSL_ENABLED}
kafka.ccm.pgp.bootstrap-servers=${KAFKA_CCM_PGP_SERVER}
kafka.ccm.pgp.consumer.group-id=${KAFKA_CCM_PGP_GROUP}
kafka.ccm.pgp.topicReq=${KAFKA_CCM_PGP_TOPIC}
kafka.ccm.pgp.schema.registry.url=${KAFKA_CCM_PGP_SCHEMA}
#ccm PTS
kafka.ccm.pts.enable=false
kafka.ccm.pts.ssl-enabled=${KAFKA_CCM_PTS_SSL_ENABLED}
kafka.ccm.pts.bootstrap-servers=${KAFKA_CCM_PTS_SERVER}
kafka.ccm.pts.consumer.group-id=${KAFKA_CCM_PTS_GROUP}
kafka.ccm.pts.topicReq=${KAFKA_CCM_PTS_TOPIC}
kafka.ccm.pts.schema.registry.url=${KAFKA_CCM_PTS_SCHEMA}
#ccm KC1
kafka.ccm.kc1.ssl-enabled=${KAFKA_CCM_KC1_SSL_ENABLED}
kafka.ccm.kc1.bootstrap-servers=${KAFKA_CCM_KC1_SERVER}
kafka.ccm.kc1.consumer.group-id=${KAFKA_CCM_KC1_GROUP}
kafka.ccm.kc1.topicReq=${KAFKA_CCM_KC1_TOPIC}
kafka.ccm.kc1.schema.registry.url=${KAFKA_CCM_KC1_SCHEMA}
#ccm KC2
kafka.ccm.kc2.ssl-enabled=${KAFKA_CCM_KC2_SSL_ENABLED}
kafka.ccm.kc2.bootstrap-servers=${KAFKA_CCM_KC2_SERVER}
kafka.ccm.kc2.consumer.group-id=${KAFKA_CCM_KC2_GROUP}
kafka.ccm.kc2.topicReq=${KAFKA_CCM_KC2_TOPIC}
kafka.ccm.kc2.schema.registry.url=${KAFKA_CCM_KC2_SCHEMA}

#pdm
kafka.pdm.ssl-enabled=${KAFKA_PDM_SSL_ENABLED}
kafka.pdm.bootstrap-servers=${KAFKA_PDM_SERVER}
kafka.pdm.schema.registry.url=${KAFKA_PDM_SCHEMA}
kafka.pdm.consumer.group-id=${KAFKA_PDM_GROUP}
kafka.pdm.topic.microstructure=${KAFKA_PDM_TOPIC_MICRO}
kafka.pdm.topic.asap-chemical-properties=${KAFKA_PDM_TOPIC_ASAP_CHEMICAL}
kafka.pdm.topic.equivalents=${KAFKA_PDM_TOPIC_EQUVALENTS}
kafka.pdm.topic.match-tk-num=${KAFKA_PDM_TOPIC_MATCH_TK_NUM}
kafka.pdm.topic.match-rabplan-num=${KAFKA_PDM_TOPIC_MATCH_RP_NUM}
kafka.pdm.topic.asap-tol-links=${KAFKA_PDM_TOPIC_ASAP_TOL_LINKS}
kafka.pdm.topic.kat-steel-4041=${KAFKA_PDM_TOPIC_STEEL_4041}
kafka.pdm.topic.tol-thick=${KAFKA_PDM_TOPIC_TOL_THICK}
kafka.pdm.topic.tol-width=${KAFKA_PDM_TOPIC_TOL_WIDTH}
kafka.pdm.topic.tol-length=${KAFKA_PDM_TOPIC_TOL_LENGTH}
kafka.pdm.topic.asap-mech-properties=${KAFKA_PDM_TOPIC_ASAP_MECH_PROP}
kafka.pdm.topic.tol-evenness=${KAFKA_PDM_TOPIC_TOL_EVENNESS}
kafka.pdm.topic.tk-num=${KAFKA_PDM_TOPIC_TK_NUM}
kafka.pdm.topic.mech-properties=${KAFKA_PDM_TOPIC_MECH_PROP}
kafka.pdm.topic.chemical-properties=${KAFKA_PDM_TOPIC_CHEMICAL_PROP}
kafka.pdm.topic.asap-mech-properties-dt=${KAFKA_PDM_TOPIC_ASAP_MECH_PROP_DT}
kafka.pdm.topic.phys-mech-prop-anis-steel=${KAFKA_PDM_TOPIC_PHYS_MECH_PROP_ANIS_STEEL}
kafka.pdm.topic.tol-evenness-dt=${KAFKA_PDM_TOPIC_TOL_EVENNESS_DT}
kafka.pdm.topic.tol-thick-dt=${KAFKA_PDM_TOPIC_TOL_THICK_DT}
kafka.pdm.topic.tol-width-dt=${KAFKA_PDM_TOPIC_TOL_WIDTH_DT}
kafka.pdm.topic.sp-chemical-properties-notes=${KAFKA_PDM_TOPIC_SP_CHEMICAL_PROPERTIES_NOTES}
kafka.pdm.topic.tol-shape-slab=${KAFKA_PDM_TOPIC_TOL_SHAPE_SLAB}
kafka.pdm.topic.register-equivalents=${KAFKA_PDM_TOPIC_REGISTER_EQUIVALENTS}
kafka.pdm.topic.min-number-samp-chem=${KAFKA_PDM_TOPIC_MIN_NUMBER_SAMP_CHEM}
kafka.pdm.topic.scheme-stripping-slab=${KAFKA_PDM_TOPIC_SCHEME_STRIPPING_SLAB}
kafka.pdm.topic.macrostructure=${KAFKA_PDM_TOPIC_MACROSTRUCTURE}
kafka.pdm.topic.type-sample-macrostructure=${KAFKA_PDM_TOPIC_TYPE_SAMPLE_MACROSTRUCTURE}
kafka.pdm.topic.coding-slab=${KAFKA_PDM_TOPIC_CODING_SLAB}
kafka.pdm.topic.choice-tested-products=${KAFKA_PDM_TOPIC_CHOICE_TESTED_PRODUCTS}
kafka.pdm.topic.corrosive-properties=${KAFKA_PDM_TOPIC_CORROSIVE_PROPERTIES}

#sadim
#kafka.sadim.bootstrap-servers=${KAFKA_SADIM_SERVER}
#kafka.sadim.group-id=${KAFKA_SADIM_GROUP}
#kafka.sadim.topic=${KAFKA_SADIM_TOPIC}
kafka.sadim.enabled=false

#SAP
kafka.sap.ssl-enabled=${KAFKA_SAP_SSL_ENABLED}
kafka.sap.bootstrap-servers=${KAFKA_SAP_SERVER}
kafka.sap.group-id=${KAFKA_SAP_GROUP}
kafka.sap.topic.s3.idoczordrs=${KAFKA_SAP_TOPIC_S3_IDOCZORDRS}
kafka.sap.topic.s3.zmmordersdop=${KAFKA_SAP_TOPIC_S3_ZMMORDERSDOP}
kafka.sap.schema.registry.url=${KAFKA_SAP_SCHEMA}

#NSI.ZIFRA
kafka.zifra.ssl-enabled=${KAFKA_ZIFRA_SSL_ENABLED}
kafka.zifra.bootstrap-servers=${KAFKA_ZIFRA_SERVER}
kafka.zifra.schema.registry.url=${KAFKA_ZIFRA_SCHEMA}
kafka.zifra.consumer.group-id=${KAFKA_ZIFRA_GROUP}
kafka.zifra.topic.sp-customer=${KAFKA_ZIFRA_TOPIC_CUSTOMER}
kafka.zifra.topic.sp-customer-group=${KAFKA_ZIFRA_TOPIC_CUSTOMER_GROUP}
kafka.zifra.topic.sp-group-and-customer=${KAFKA_ZIFRA_TOPIC_GROUP_AND_CUSTOMER}
kafka.zifra.topic.sp-om-data-type=${KAFKA_ZIFRA_TOPIC_OM_DATA_TYPE}
kafka.zifra.topic.sp-attributes=${KAFKA_ZIFRA_TOPIC_ATTRIBUTES}
kafka.zifra.topic.sp-l2code-place=${KAFKA_ZIFRA_TOPIC_PLACE}
kafka.zifra.topic.sp-attribute-attestation-group=${KAFKA_ZIFRA_TOPIC_ATTRIBUTE_ATTESTATION_GROUP}
kafka.zifra.topic.sp-measure=${KAFKA_ZIFRA_TOPIC_MEASURE}
kafka.zifra.topic.sp-data-type=${KAFKA_ZIFRA_TOPIC_DATA_TYPE}
kafka.zifra.topic.sp-analysis-type=${KAFKA_ZIFRA_TOPIC_ANALYSIS_TYPE}
kafka.zifra.topic.sp-certification-step-type=${KAFKA_ZIFRA_TOPIC_CERTIFICATION_STEP_TYPE}
kafka.zifra.topic.sp-sampling-topology=${KAFKA_ZIFRA_TOPIC_SAMPLING_TOPOLOGY}
kafka.zifra.topic.sp-dimension=${KAFKA_ZIFRA_TOPIC_DIMENSION}
kafka.zifra.topic.sp-place-type=${KAFKA_ZIFRA_TOPIC_PLACE_TYPE}
kafka.zifra.topic.sp-mapping-attribute-ccm3t=${KAFKA_ZIFRA_TOPIC_MAPPING_ATTRIBUTE_CCM3T}
kafka.zifra.topic.sp-test-type-request=${KAFKA_ZIFRA_TOPIC_TEST_TYPE_REQUEST}
kafka.zifra.topic.sp-distribution-type=${KAFKA_ZIFRA_TOPIC_DISTRIBUTION_TYPE}

#S3
s3.url=${S3_URL}
s3.idoczordrs.access-key=${S3_IDOCZORDRS_ACCESS_KEY}
s3.idoczordrs.secret-key=${S3_IDOCZORDRS_SECRET_KEY}
s3.idoczordrs.bucket-name=${S3_IDOCZORDRS_BUCKET_NAME}
s3.zmmordersdop.access-key=${S3_ZMMORDERSDOP_ACCESS_KEY}
s3.zmmordersdop.secret-key=${S3_ZMMORDERSDOP_SECRET_KEY}
s3.zmmordersdop.bucket-name=${S3_ZMMORDERSDOP_BUCKET_NAME}

#protected resource: token + authRole + pattern
#other resource - unprotected (public)
keycloak.securityConstraints[0].authRoles[0]=change-config-pdm
keycloak.securityConstraints[0].securityCollections[0].methods[0]=PUT
keycloak.securityConstraints[0].securityCollections[0].methods[1]=DELETE
keycloak.securityConstraints[0].securityCollections[0].patterns[0]=/dict/configuration/*
keycloak.securityConstraints[1].authRoles[0]=delete-pdm-message
keycloak.securityConstraints[1].securityCollections[0].methods[0]=DELETE
keycloak.securityConstraints[1].securityCollections[0].patterns[0]=/pdm_message/*
keycloak.securityConstraints[2].authRoles[0]=process-pdm-message
keycloak.securityConstraints[2].securityCollections[0].methods[0]=POST
keycloak.securityConstraints[2].securityCollections[0].patterns[0]=/pdm_message/*
keycloak.securityConstraints[3].authRoles[0]=create-attestation-request
keycloak.securityConstraints[3].securityCollections[0].methods[0]=GET
keycloak.securityConstraints[3].securityCollections[0].patterns[0]=/launch_attestation/*
keycloak.securityConstraints[4].authRoles[0]=process-sap-message
keycloak.securityConstraints[4].securityCollections[0].methods[0]=GET
keycloak.securityConstraints[4].securityCollections[0].methods[1]=POST
keycloak.securityConstraints[4].securityCollections[0].patterns[0]=/sap_message/*
keycloak.securityConstraints[5].authRoles[0]=cdc-processing
keycloak.securityConstraints[5].securityCollections[0].methods[0]=POST
keycloak.securityConstraints[5].securityCollections[0].patterns[0]=/cdc/*


application.version=@project.version@
application.name=@project.name@
application.description=@project.description@
