spring.application.name=kb-module
spring.jackson.deserialization.fail_on_unknown_properties=false

logging.file.name=kb-module.log
server.port=8089

spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.generate-ddl=false
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false

keycloak.auth-server-url=http://127.0.0.1:7080/auth
keycloak.realm=BackEndApp
keycloak.resource=app-server
keycloak.bearer-only=true

#protected resource: token + authRole + pattern
#other resource - unprotected (public)
#TEMP#keycloak.securityConstraints[0].authRoles[0] = app-users
#TEMP#keycloak.securityConstraints[0].securityCollections[0].patterns[0] = /nsi/*

spring.profiles.active=prod

pam.url=pam.attestation.url=${PAM_SERVER_BASEURL}/attestation

kafka.sup.bootstrap-servers = nl-sq-dpltkfk01.ao.nlmk:9092
kafka.sup.consumer.group-id = service-prod.app-apcs.kb
kafka.sup.topicIp = 000-1.l3-sup.db.nlmk.integral-parameters.0
kafka.sup.topicUp = 000-1.l3-sup.db.nlmk.unrecoverable-parameters-trends.0
kafka.schema.registry.url =  http://kafka-rest-000-1.dp.nlmk.com:8081

kafka.ccm.bootstrap-servers = nl-sq-dpltkfk01.ao.nlmk:9092
kafka.ccm.consumer.group-id = service-prod.app-apcs.kb.attest-request
kafka.ccm.topicReq = 000-1.l3-ccm-pgp.db.Attestation-Request.0