spring.application.name=kb-module
spring.jackson.deserialization.fail_on_unknown_properties=false

logging.file.name=kb-module.log
logging.pattern.console=%clr(%d{${LOG_DATEFORMAT_PATTERN:-yyyy-MM-dd HH:mm:ss.SSS}}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr( %X{requestID}:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}
logging.pattern.file=%d{${LOG_DATEFORMAT_PATTERN:-yyyy-MM-dd HH:mm:ss.SSS}} ${LOG_LEVEL_PATTERN:-%5p} ${PID:- } --- [%t] %-40.40logger{39} %X{requestID}: %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}

server.port=8089

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.disable-swagger-default-url=true

spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/kbs
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=kbs
spring.datasource.password=kbs
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

keycloak.auth-server-url=http://127.0.0.1:7080/auth
keycloak.realm=BackEndApp
keycloak.resource=app-server
keycloak.bearer-only=true

#protected resource: token + authRole + pattern
#other resource - unprotected (public)
#TEMP#keycloak.securityConstraints[0].authRoles[0] = app-users
#TEMP#keycloak.securityConstraints[0].securityCollections[0].patterns[0] = /nsi/*

spring.profiles.active=dev