/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package nlmk.mes.cgp.asap.adapter.analysis.request.v0;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class AsapResponse extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -4159204376035872855L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"AsapResponse\",\"namespace\":\"nlmk.mes.cgp.asap.adapter.analysis.request.v0\",\"fields\":[{\"name\":\"mismatch\",\"type\":\"int\",\"doc\":\"Код результата аттестации АСАП\"},{\"name\":\"note\",\"type\":[\"null\",\"string\"],\"doc\":\"Источник допустимых значений показателей качества\",\"default\":null},{\"name\":\"norms\",\"type\":{\"type\":\"record\",\"name\":\"Norms\",\"fields\":[{\"name\":\"valueMin\",\"type\":[\"null\",\"string\"],\"doc\":\"Минимально допустимое значение\",\"default\":null},{\"name\":\"valueMax\",\"type\":[\"null\",\"string\"],\"doc\":\"Максимально допустимое значение\",\"default\":null}]}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<AsapResponse> ENCODER =
      new BinaryMessageEncoder<AsapResponse>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<AsapResponse> DECODER =
      new BinaryMessageDecoder<AsapResponse>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<AsapResponse> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<AsapResponse> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<AsapResponse> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<AsapResponse>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this AsapResponse to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a AsapResponse from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a AsapResponse instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static AsapResponse fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** Код результата аттестации АСАП */
   private int mismatch;
  /** Источник допустимых значений показателей качества */
   private java.lang.CharSequence note;
   private nlmk.mes.cgp.asap.adapter.analysis.request.v0.Norms norms;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public AsapResponse() {}

  /**
   * All-args constructor.
   * @param mismatch Код результата аттестации АСАП
   * @param note Источник допустимых значений показателей качества
   * @param norms The new value for norms
   */
  public AsapResponse(java.lang.Integer mismatch, java.lang.CharSequence note, nlmk.mes.cgp.asap.adapter.analysis.request.v0.Norms norms) {
    this.mismatch = mismatch;
    this.note = note;
    this.norms = norms;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return mismatch;
    case 1: return note;
    case 2: return norms;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: mismatch = (java.lang.Integer)value$; break;
    case 1: note = (java.lang.CharSequence)value$; break;
    case 2: norms = (nlmk.mes.cgp.asap.adapter.analysis.request.v0.Norms)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'mismatch' field.
   * @return Код результата аттестации АСАП
   */
  public int getMismatch() {
    return mismatch;
  }


  /**
   * Sets the value of the 'mismatch' field.
   * Код результата аттестации АСАП
   * @param value the value to set.
   */
  public void setMismatch(int value) {
    this.mismatch = value;
  }

  /**
   * Gets the value of the 'note' field.
   * @return Источник допустимых значений показателей качества
   */
  public java.lang.CharSequence getNote() {
    return note;
  }


  /**
   * Sets the value of the 'note' field.
   * Источник допустимых значений показателей качества
   * @param value the value to set.
   */
  public void setNote(java.lang.CharSequence value) {
    this.note = value;
  }

  /**
   * Gets the value of the 'norms' field.
   * @return The value of the 'norms' field.
   */
  public nlmk.mes.cgp.asap.adapter.analysis.request.v0.Norms getNorms() {
    return norms;
  }


  /**
   * Sets the value of the 'norms' field.
   * @param value the value to set.
   */
  public void setNorms(nlmk.mes.cgp.asap.adapter.analysis.request.v0.Norms value) {
    this.norms = value;
  }

  /**
   * Creates a new AsapResponse RecordBuilder.
   * @return A new AsapResponse RecordBuilder
   */
  public static nlmk.mes.cgp.asap.adapter.analysis.request.v0.AsapResponse.Builder newBuilder() {
    return new nlmk.mes.cgp.asap.adapter.analysis.request.v0.AsapResponse.Builder();
  }

  /**
   * Creates a new AsapResponse RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new AsapResponse RecordBuilder
   */
  public static nlmk.mes.cgp.asap.adapter.analysis.request.v0.AsapResponse.Builder newBuilder(nlmk.mes.cgp.asap.adapter.analysis.request.v0.AsapResponse.Builder other) {
    if (other == null) {
      return new nlmk.mes.cgp.asap.adapter.analysis.request.v0.AsapResponse.Builder();
    } else {
      return new nlmk.mes.cgp.asap.adapter.analysis.request.v0.AsapResponse.Builder(other);
    }
  }

  /**
   * Creates a new AsapResponse RecordBuilder by copying an existing AsapResponse instance.
   * @param other The existing instance to copy.
   * @return A new AsapResponse RecordBuilder
   */
  public static nlmk.mes.cgp.asap.adapter.analysis.request.v0.AsapResponse.Builder newBuilder(nlmk.mes.cgp.asap.adapter.analysis.request.v0.AsapResponse other) {
    if (other == null) {
      return new nlmk.mes.cgp.asap.adapter.analysis.request.v0.AsapResponse.Builder();
    } else {
      return new nlmk.mes.cgp.asap.adapter.analysis.request.v0.AsapResponse.Builder(other);
    }
  }

  /**
   * RecordBuilder for AsapResponse instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<AsapResponse>
    implements org.apache.avro.data.RecordBuilder<AsapResponse> {

    /** Код результата аттестации АСАП */
    private int mismatch;
    /** Источник допустимых значений показателей качества */
    private java.lang.CharSequence note;
    private nlmk.mes.cgp.asap.adapter.analysis.request.v0.Norms norms;
    private nlmk.mes.cgp.asap.adapter.analysis.request.v0.Norms.Builder normsBuilder;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(nlmk.mes.cgp.asap.adapter.analysis.request.v0.AsapResponse.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.mismatch)) {
        this.mismatch = data().deepCopy(fields()[0].schema(), other.mismatch);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.note)) {
        this.note = data().deepCopy(fields()[1].schema(), other.note);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.norms)) {
        this.norms = data().deepCopy(fields()[2].schema(), other.norms);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (other.hasNormsBuilder()) {
        this.normsBuilder = nlmk.mes.cgp.asap.adapter.analysis.request.v0.Norms.newBuilder(other.getNormsBuilder());
      }
    }

    /**
     * Creates a Builder by copying an existing AsapResponse instance
     * @param other The existing instance to copy.
     */
    private Builder(nlmk.mes.cgp.asap.adapter.analysis.request.v0.AsapResponse other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.mismatch)) {
        this.mismatch = data().deepCopy(fields()[0].schema(), other.mismatch);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.note)) {
        this.note = data().deepCopy(fields()[1].schema(), other.note);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.norms)) {
        this.norms = data().deepCopy(fields()[2].schema(), other.norms);
        fieldSetFlags()[2] = true;
      }
      this.normsBuilder = null;
    }

    /**
      * Gets the value of the 'mismatch' field.
      * Код результата аттестации АСАП
      * @return The value.
      */
    public int getMismatch() {
      return mismatch;
    }


    /**
      * Sets the value of the 'mismatch' field.
      * Код результата аттестации АСАП
      * @param value The value of 'mismatch'.
      * @return This builder.
      */
    public nlmk.mes.cgp.asap.adapter.analysis.request.v0.AsapResponse.Builder setMismatch(int value) {
      validate(fields()[0], value);
      this.mismatch = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'mismatch' field has been set.
      * Код результата аттестации АСАП
      * @return True if the 'mismatch' field has been set, false otherwise.
      */
    public boolean hasMismatch() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'mismatch' field.
      * Код результата аттестации АСАП
      * @return This builder.
      */
    public nlmk.mes.cgp.asap.adapter.analysis.request.v0.AsapResponse.Builder clearMismatch() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'note' field.
      * Источник допустимых значений показателей качества
      * @return The value.
      */
    public java.lang.CharSequence getNote() {
      return note;
    }


    /**
      * Sets the value of the 'note' field.
      * Источник допустимых значений показателей качества
      * @param value The value of 'note'.
      * @return This builder.
      */
    public nlmk.mes.cgp.asap.adapter.analysis.request.v0.AsapResponse.Builder setNote(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.note = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'note' field has been set.
      * Источник допустимых значений показателей качества
      * @return True if the 'note' field has been set, false otherwise.
      */
    public boolean hasNote() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'note' field.
      * Источник допустимых значений показателей качества
      * @return This builder.
      */
    public nlmk.mes.cgp.asap.adapter.analysis.request.v0.AsapResponse.Builder clearNote() {
      note = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'norms' field.
      * @return The value.
      */
    public nlmk.mes.cgp.asap.adapter.analysis.request.v0.Norms getNorms() {
      return norms;
    }


    /**
      * Sets the value of the 'norms' field.
      * @param value The value of 'norms'.
      * @return This builder.
      */
    public nlmk.mes.cgp.asap.adapter.analysis.request.v0.AsapResponse.Builder setNorms(nlmk.mes.cgp.asap.adapter.analysis.request.v0.Norms value) {
      validate(fields()[2], value);
      this.normsBuilder = null;
      this.norms = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'norms' field has been set.
      * @return True if the 'norms' field has been set, false otherwise.
      */
    public boolean hasNorms() {
      return fieldSetFlags()[2];
    }

    /**
     * Gets the Builder instance for the 'norms' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public nlmk.mes.cgp.asap.adapter.analysis.request.v0.Norms.Builder getNormsBuilder() {
      if (normsBuilder == null) {
        if (hasNorms()) {
          setNormsBuilder(nlmk.mes.cgp.asap.adapter.analysis.request.v0.Norms.newBuilder(norms));
        } else {
          setNormsBuilder(nlmk.mes.cgp.asap.adapter.analysis.request.v0.Norms.newBuilder());
        }
      }
      return normsBuilder;
    }

    /**
     * Sets the Builder instance for the 'norms' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */

    public nlmk.mes.cgp.asap.adapter.analysis.request.v0.AsapResponse.Builder setNormsBuilder(nlmk.mes.cgp.asap.adapter.analysis.request.v0.Norms.Builder value) {
      clearNorms();
      normsBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'norms' field has an active Builder instance
     * @return True if the 'norms' field has an active Builder instance
     */
    public boolean hasNormsBuilder() {
      return normsBuilder != null;
    }

    /**
      * Clears the value of the 'norms' field.
      * @return This builder.
      */
    public nlmk.mes.cgp.asap.adapter.analysis.request.v0.AsapResponse.Builder clearNorms() {
      norms = null;
      normsBuilder = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public AsapResponse build() {
      try {
        AsapResponse record = new AsapResponse();
        record.mismatch = fieldSetFlags()[0] ? this.mismatch : (java.lang.Integer) defaultValue(fields()[0]);
        record.note = fieldSetFlags()[1] ? this.note : (java.lang.CharSequence) defaultValue(fields()[1]);
        if (normsBuilder != null) {
          try {
            record.norms = this.normsBuilder.build();
          } catch (org.apache.avro.AvroMissingFieldException e) {
            e.addParentField(record.getSchema().getField("norms"));
            throw e;
          }
        } else {
          record.norms = fieldSetFlags()[2] ? this.norms : (nlmk.mes.cgp.asap.adapter.analysis.request.v0.Norms) defaultValue(fields()[2]);
        }
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<AsapResponse>
    WRITER$ = (org.apache.avro.io.DatumWriter<AsapResponse>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<AsapResponse>
    READER$ = (org.apache.avro.io.DatumReader<AsapResponse>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeInt(this.mismatch);

    if (this.note == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.note);
    }

    this.norms.customEncode(out);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.mismatch = in.readInt();

      if (in.readIndex() != 1) {
        in.readNull();
        this.note = null;
      } else {
        this.note = in.readString(this.note instanceof Utf8 ? (Utf8)this.note : null);
      }

      if (this.norms == null) {
        this.norms = new nlmk.mes.cgp.asap.adapter.analysis.request.v0.Norms();
      }
      this.norms.customDecode(in);

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.mismatch = in.readInt();
          break;

        case 1:
          if (in.readIndex() != 1) {
            in.readNull();
            this.note = null;
          } else {
            this.note = in.readString(this.note instanceof Utf8 ? (Utf8)this.note : null);
          }
          break;

        case 2:
          if (this.norms == null) {
            this.norms = new nlmk.mes.cgp.asap.adapter.analysis.request.v0.Norms();
          }
          this.norms.customDecode(in);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










