/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package nlmk.mes.cgp.asap.adapter.analysis.request.v0;
@org.apache.avro.specific.AvroGenerated
public enum EnumOp implements org.apache.avro.generic.GenericEnumSymbol<EnumOp> {
  I, U, D  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"EnumOp\",\"namespace\":\"nlmk.mes.cgp.asap.adapter.analysis.request.v0\",\"symbols\":[\"I\",\"U\",\"D\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
