/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package nlmk.mes.cgp.asap.adapter.analysis.request.v0;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class PkType extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -4419964713787263225L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"PkType\",\"namespace\":\"nlmk.mes.cgp.asap.adapter.analysis.request.v0\",\"fields\":[{\"name\":\"systemCode\",\"type\":\"string\",\"doc\":\"Код системы\"},{\"name\":\"metalUnitId\",\"type\":\"string\",\"doc\":\"Идентификатор единицы складского учета\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<PkType> ENCODER =
      new BinaryMessageEncoder<PkType>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<PkType> DECODER =
      new BinaryMessageDecoder<PkType>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<PkType> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<PkType> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<PkType> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<PkType>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this PkType to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a PkType from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a PkType instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static PkType fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** Код системы */
   private java.lang.CharSequence systemCode;
  /** Идентификатор единицы складского учета */
   private java.lang.CharSequence metalUnitId;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public PkType() {}

  /**
   * All-args constructor.
   * @param systemCode Код системы
   * @param metalUnitId Идентификатор единицы складского учета
   */
  public PkType(java.lang.CharSequence systemCode, java.lang.CharSequence metalUnitId) {
    this.systemCode = systemCode;
    this.metalUnitId = metalUnitId;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return systemCode;
    case 1: return metalUnitId;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: systemCode = (java.lang.CharSequence)value$; break;
    case 1: metalUnitId = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'systemCode' field.
   * @return Код системы
   */
  public java.lang.CharSequence getSystemCode() {
    return systemCode;
  }


  /**
   * Sets the value of the 'systemCode' field.
   * Код системы
   * @param value the value to set.
   */
  public void setSystemCode(java.lang.CharSequence value) {
    this.systemCode = value;
  }

  /**
   * Gets the value of the 'metalUnitId' field.
   * @return Идентификатор единицы складского учета
   */
  public java.lang.CharSequence getMetalUnitId() {
    return metalUnitId;
  }


  /**
   * Sets the value of the 'metalUnitId' field.
   * Идентификатор единицы складского учета
   * @param value the value to set.
   */
  public void setMetalUnitId(java.lang.CharSequence value) {
    this.metalUnitId = value;
  }

  /**
   * Creates a new PkType RecordBuilder.
   * @return A new PkType RecordBuilder
   */
  public static nlmk.mes.cgp.asap.adapter.analysis.request.v0.PkType.Builder newBuilder() {
    return new nlmk.mes.cgp.asap.adapter.analysis.request.v0.PkType.Builder();
  }

  /**
   * Creates a new PkType RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new PkType RecordBuilder
   */
  public static nlmk.mes.cgp.asap.adapter.analysis.request.v0.PkType.Builder newBuilder(nlmk.mes.cgp.asap.adapter.analysis.request.v0.PkType.Builder other) {
    if (other == null) {
      return new nlmk.mes.cgp.asap.adapter.analysis.request.v0.PkType.Builder();
    } else {
      return new nlmk.mes.cgp.asap.adapter.analysis.request.v0.PkType.Builder(other);
    }
  }

  /**
   * Creates a new PkType RecordBuilder by copying an existing PkType instance.
   * @param other The existing instance to copy.
   * @return A new PkType RecordBuilder
   */
  public static nlmk.mes.cgp.asap.adapter.analysis.request.v0.PkType.Builder newBuilder(nlmk.mes.cgp.asap.adapter.analysis.request.v0.PkType other) {
    if (other == null) {
      return new nlmk.mes.cgp.asap.adapter.analysis.request.v0.PkType.Builder();
    } else {
      return new nlmk.mes.cgp.asap.adapter.analysis.request.v0.PkType.Builder(other);
    }
  }

  /**
   * RecordBuilder for PkType instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<PkType>
    implements org.apache.avro.data.RecordBuilder<PkType> {

    /** Код системы */
    private java.lang.CharSequence systemCode;
    /** Идентификатор единицы складского учета */
    private java.lang.CharSequence metalUnitId;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(nlmk.mes.cgp.asap.adapter.analysis.request.v0.PkType.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.systemCode)) {
        this.systemCode = data().deepCopy(fields()[0].schema(), other.systemCode);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.metalUnitId)) {
        this.metalUnitId = data().deepCopy(fields()[1].schema(), other.metalUnitId);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing PkType instance
     * @param other The existing instance to copy.
     */
    private Builder(nlmk.mes.cgp.asap.adapter.analysis.request.v0.PkType other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.systemCode)) {
        this.systemCode = data().deepCopy(fields()[0].schema(), other.systemCode);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.metalUnitId)) {
        this.metalUnitId = data().deepCopy(fields()[1].schema(), other.metalUnitId);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'systemCode' field.
      * Код системы
      * @return The value.
      */
    public java.lang.CharSequence getSystemCode() {
      return systemCode;
    }


    /**
      * Sets the value of the 'systemCode' field.
      * Код системы
      * @param value The value of 'systemCode'.
      * @return This builder.
      */
    public nlmk.mes.cgp.asap.adapter.analysis.request.v0.PkType.Builder setSystemCode(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.systemCode = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'systemCode' field has been set.
      * Код системы
      * @return True if the 'systemCode' field has been set, false otherwise.
      */
    public boolean hasSystemCode() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'systemCode' field.
      * Код системы
      * @return This builder.
      */
    public nlmk.mes.cgp.asap.adapter.analysis.request.v0.PkType.Builder clearSystemCode() {
      systemCode = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'metalUnitId' field.
      * Идентификатор единицы складского учета
      * @return The value.
      */
    public java.lang.CharSequence getMetalUnitId() {
      return metalUnitId;
    }


    /**
      * Sets the value of the 'metalUnitId' field.
      * Идентификатор единицы складского учета
      * @param value The value of 'metalUnitId'.
      * @return This builder.
      */
    public nlmk.mes.cgp.asap.adapter.analysis.request.v0.PkType.Builder setMetalUnitId(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.metalUnitId = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'metalUnitId' field has been set.
      * Идентификатор единицы складского учета
      * @return True if the 'metalUnitId' field has been set, false otherwise.
      */
    public boolean hasMetalUnitId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'metalUnitId' field.
      * Идентификатор единицы складского учета
      * @return This builder.
      */
    public nlmk.mes.cgp.asap.adapter.analysis.request.v0.PkType.Builder clearMetalUnitId() {
      metalUnitId = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public PkType build() {
      try {
        PkType record = new PkType();
        record.systemCode = fieldSetFlags()[0] ? this.systemCode : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.metalUnitId = fieldSetFlags()[1] ? this.metalUnitId : (java.lang.CharSequence) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<PkType>
    WRITER$ = (org.apache.avro.io.DatumWriter<PkType>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<PkType>
    READER$ = (org.apache.avro.io.DatumReader<PkType>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.systemCode);

    out.writeString(this.metalUnitId);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.systemCode = in.readString(this.systemCode instanceof Utf8 ? (Utf8)this.systemCode : null);

      this.metalUnitId = in.readString(this.metalUnitId instanceof Utf8 ? (Utf8)this.metalUnitId : null);

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.systemCode = in.readString(this.systemCode instanceof Utf8 ? (Utf8)this.systemCode : null);
          break;

        case 1:
          this.metalUnitId = in.readString(this.metalUnitId instanceof Utf8 ? (Utf8)this.metalUnitId : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










