/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package nlmk.mes.cgp.asap.adapter.analysis.request.v0;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

/** Массив качественных характеристик проведенных испытаний */
@org.apache.avro.specific.AvroGenerated
public class RecordQualityIndicators extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -5162920555228750552L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"RecordQualityIndicators\",\"namespace\":\"nlmk.mes.cgp.asap.adapter.analysis.request.v0\",\"doc\":\"Массив качественных характеристик проведенных испытаний\",\"fields\":[{\"name\":\"attrId\",\"type\":\"string\",\"doc\":\"Guid качественной характеристики\"},{\"name\":\"attrName\",\"type\":\"string\",\"doc\":\"Наименование качественной характеристики\"},{\"name\":\"dataTypePhysical\",\"type\":\"string\",\"doc\":\"Константа обозначения физического типа AVRO\"},{\"name\":\"relation\",\"type\":{\"type\":\"enum\",\"name\":\"Relation\",\"doc\":\"Оператор сравнения\",\"symbols\":[\"EQUAL\",\"MORE\",\"LESS\"]}},{\"name\":\"value\",\"type\":\"string\",\"doc\":\"Значение качественной характеристики\"},{\"name\":\"measure\",\"type\":[\"null\",{\"type\":\"record\",\"name\":\"RecordMeasure\",\"fields\":[{\"name\":\"measureId\",\"type\":\"string\",\"doc\":\"Guid единицы измерения\"},{\"name\":\"measureName\",\"type\":\"string\",\"doc\":\"Наименование единицы измерения\"}]}]},{\"name\":\"addProperties\",\"type\":[\"null\",{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"RecordAddProperties\",\"doc\":\"Дополнительные свойства характеристики\",\"fields\":[{\"name\":\"attrId\",\"type\":\"string\",\"doc\":\"Guid качественной характеристики\"},{\"name\":\"attrName\",\"type\":\"string\",\"doc\":\"Наименование качественной характеристики\"},{\"name\":\"dataTypePhysical\",\"type\":\"string\",\"doc\":\"Константа обозначения физического типа AVRO\"},{\"name\":\"relation\",\"type\":\"Relation\"},{\"name\":\"value\",\"type\":\"string\",\"doc\":\"Значение качественной характеристики\"},{\"name\":\"measure\",\"type\":[\"null\",\"RecordMeasure\"]}]},\"default\":null}]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<RecordQualityIndicators> ENCODER =
      new BinaryMessageEncoder<RecordQualityIndicators>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<RecordQualityIndicators> DECODER =
      new BinaryMessageDecoder<RecordQualityIndicators>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<RecordQualityIndicators> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<RecordQualityIndicators> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<RecordQualityIndicators> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<RecordQualityIndicators>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this RecordQualityIndicators to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a RecordQualityIndicators from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a RecordQualityIndicators instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static RecordQualityIndicators fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** Guid качественной характеристики */
   private java.lang.CharSequence attrId;
  /** Наименование качественной характеристики */
   private java.lang.CharSequence attrName;
  /** Константа обозначения физического типа AVRO */
   private java.lang.CharSequence dataTypePhysical;
   private nlmk.mes.cgp.asap.adapter.analysis.request.v0.Relation relation;
  /** Значение качественной характеристики */
   private java.lang.CharSequence value;
   private nlmk.mes.cgp.asap.adapter.analysis.request.v0.RecordMeasure measure;
   private java.util.List<nlmk.mes.cgp.asap.adapter.analysis.request.v0.RecordAddProperties> addProperties;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public RecordQualityIndicators() {}

  /**
   * All-args constructor.
   * @param attrId Guid качественной характеристики
   * @param attrName Наименование качественной характеристики
   * @param dataTypePhysical Константа обозначения физического типа AVRO
   * @param relation The new value for relation
   * @param value Значение качественной характеристики
   * @param measure The new value for measure
   * @param addProperties The new value for addProperties
   */
  public RecordQualityIndicators(java.lang.CharSequence attrId, java.lang.CharSequence attrName, java.lang.CharSequence dataTypePhysical, nlmk.mes.cgp.asap.adapter.analysis.request.v0.Relation relation, java.lang.CharSequence value, nlmk.mes.cgp.asap.adapter.analysis.request.v0.RecordMeasure measure, java.util.List<nlmk.mes.cgp.asap.adapter.analysis.request.v0.RecordAddProperties> addProperties) {
    this.attrId = attrId;
    this.attrName = attrName;
    this.dataTypePhysical = dataTypePhysical;
    this.relation = relation;
    this.value = value;
    this.measure = measure;
    this.addProperties = addProperties;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return attrId;
    case 1: return attrName;
    case 2: return dataTypePhysical;
    case 3: return relation;
    case 4: return value;
    case 5: return measure;
    case 6: return addProperties;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: attrId = (java.lang.CharSequence)value$; break;
    case 1: attrName = (java.lang.CharSequence)value$; break;
    case 2: dataTypePhysical = (java.lang.CharSequence)value$; break;
    case 3: relation = (nlmk.mes.cgp.asap.adapter.analysis.request.v0.Relation)value$; break;
    case 4: value = (java.lang.CharSequence)value$; break;
    case 5: measure = (nlmk.mes.cgp.asap.adapter.analysis.request.v0.RecordMeasure)value$; break;
    case 6: addProperties = (java.util.List<nlmk.mes.cgp.asap.adapter.analysis.request.v0.RecordAddProperties>)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'attrId' field.
   * @return Guid качественной характеристики
   */
  public java.lang.CharSequence getAttrId() {
    return attrId;
  }


  /**
   * Sets the value of the 'attrId' field.
   * Guid качественной характеристики
   * @param value the value to set.
   */
  public void setAttrId(java.lang.CharSequence value) {
    this.attrId = value;
  }

  /**
   * Gets the value of the 'attrName' field.
   * @return Наименование качественной характеристики
   */
  public java.lang.CharSequence getAttrName() {
    return attrName;
  }


  /**
   * Sets the value of the 'attrName' field.
   * Наименование качественной характеристики
   * @param value the value to set.
   */
  public void setAttrName(java.lang.CharSequence value) {
    this.attrName = value;
  }

  /**
   * Gets the value of the 'dataTypePhysical' field.
   * @return Константа обозначения физического типа AVRO
   */
  public java.lang.CharSequence getDataTypePhysical() {
    return dataTypePhysical;
  }


  /**
   * Sets the value of the 'dataTypePhysical' field.
   * Константа обозначения физического типа AVRO
   * @param value the value to set.
   */
  public void setDataTypePhysical(java.lang.CharSequence value) {
    this.dataTypePhysical = value;
  }

  /**
   * Gets the value of the 'relation' field.
   * @return The value of the 'relation' field.
   */
  public nlmk.mes.cgp.asap.adapter.analysis.request.v0.Relation getRelation() {
    return relation;
  }


  /**
   * Sets the value of the 'relation' field.
   * @param value the value to set.
   */
  public void setRelation(nlmk.mes.cgp.asap.adapter.analysis.request.v0.Relation value) {
    this.relation = value;
  }

  /**
   * Gets the value of the 'value' field.
   * @return Значение качественной характеристики
   */
  public java.lang.CharSequence getValue() {
    return value;
  }


  /**
   * Sets the value of the 'value' field.
   * Значение качественной характеристики
   * @param value the value to set.
   */
  public void setValue(java.lang.CharSequence value) {
    this.value = value;
  }

  /**
   * Gets the value of the 'measure' field.
   * @return The value of the 'measure' field.
   */
  public nlmk.mes.cgp.asap.adapter.analysis.request.v0.RecordMeasure getMeasure() {
    return measure;
  }


  /**
   * Sets the value of the 'measure' field.
   * @param value the value to set.
   */
  public void setMeasure(nlmk.mes.cgp.asap.adapter.analysis.request.v0.RecordMeasure value) {
    this.measure = value;
  }

  /**
   * Gets the value of the 'addProperties' field.
   * @return The value of the 'addProperties' field.
   */
  public java.util.List<nlmk.mes.cgp.asap.adapter.analysis.request.v0.RecordAddProperties> getAddProperties() {
    return addProperties;
  }


  /**
   * Sets the value of the 'addProperties' field.
   * @param value the value to set.
   */
  public void setAddProperties(java.util.List<nlmk.mes.cgp.asap.adapter.analysis.request.v0.RecordAddProperties> value) {
    this.addProperties = value;
  }

  /**
   * Creates a new RecordQualityIndicators RecordBuilder.
   * @return A new RecordQualityIndicators RecordBuilder
   */
  public static nlmk.mes.cgp.asap.adapter.analysis.request.v0.RecordQualityIndicators.Builder newBuilder() {
    return new nlmk.mes.cgp.asap.adapter.analysis.request.v0.RecordQualityIndicators.Builder();
  }

  /**
   * Creates a new RecordQualityIndicators RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new RecordQualityIndicators RecordBuilder
   */
  public static nlmk.mes.cgp.asap.adapter.analysis.request.v0.RecordQualityIndicators.Builder newBuilder(nlmk.mes.cgp.asap.adapter.analysis.request.v0.RecordQualityIndicators.Builder other) {
    if (other == null) {
      return new nlmk.mes.cgp.asap.adapter.analysis.request.v0.RecordQualityIndicators.Builder();
    } else {
      return new nlmk.mes.cgp.asap.adapter.analysis.request.v0.RecordQualityIndicators.Builder(other);
    }
  }

  /**
   * Creates a new RecordQualityIndicators RecordBuilder by copying an existing RecordQualityIndicators instance.
   * @param other The existing instance to copy.
   * @return A new RecordQualityIndicators RecordBuilder
   */
  public static nlmk.mes.cgp.asap.adapter.analysis.request.v0.RecordQualityIndicators.Builder newBuilder(nlmk.mes.cgp.asap.adapter.analysis.request.v0.RecordQualityIndicators other) {
    if (other == null) {
      return new nlmk.mes.cgp.asap.adapter.analysis.request.v0.RecordQualityIndicators.Builder();
    } else {
      return new nlmk.mes.cgp.asap.adapter.analysis.request.v0.RecordQualityIndicators.Builder(other);
    }
  }

  /**
   * RecordBuilder for RecordQualityIndicators instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<RecordQualityIndicators>
    implements org.apache.avro.data.RecordBuilder<RecordQualityIndicators> {

    /** Guid качественной характеристики */
    private java.lang.CharSequence attrId;
    /** Наименование качественной характеристики */
    private java.lang.CharSequence attrName;
    /** Константа обозначения физического типа AVRO */
    private java.lang.CharSequence dataTypePhysical;
    private nlmk.mes.cgp.asap.adapter.analysis.request.v0.Relation relation;
    /** Значение качественной характеристики */
    private java.lang.CharSequence value;
    private nlmk.mes.cgp.asap.adapter.analysis.request.v0.RecordMeasure measure;
    private nlmk.mes.cgp.asap.adapter.analysis.request.v0.RecordMeasure.Builder measureBuilder;
    private java.util.List<nlmk.mes.cgp.asap.adapter.analysis.request.v0.RecordAddProperties> addProperties;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(nlmk.mes.cgp.asap.adapter.analysis.request.v0.RecordQualityIndicators.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.attrId)) {
        this.attrId = data().deepCopy(fields()[0].schema(), other.attrId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.attrName)) {
        this.attrName = data().deepCopy(fields()[1].schema(), other.attrName);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.dataTypePhysical)) {
        this.dataTypePhysical = data().deepCopy(fields()[2].schema(), other.dataTypePhysical);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.relation)) {
        this.relation = data().deepCopy(fields()[3].schema(), other.relation);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.value)) {
        this.value = data().deepCopy(fields()[4].schema(), other.value);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.measure)) {
        this.measure = data().deepCopy(fields()[5].schema(), other.measure);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (other.hasMeasureBuilder()) {
        this.measureBuilder = nlmk.mes.cgp.asap.adapter.analysis.request.v0.RecordMeasure.newBuilder(other.getMeasureBuilder());
      }
      if (isValidValue(fields()[6], other.addProperties)) {
        this.addProperties = data().deepCopy(fields()[6].schema(), other.addProperties);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
    }

    /**
     * Creates a Builder by copying an existing RecordQualityIndicators instance
     * @param other The existing instance to copy.
     */
    private Builder(nlmk.mes.cgp.asap.adapter.analysis.request.v0.RecordQualityIndicators other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.attrId)) {
        this.attrId = data().deepCopy(fields()[0].schema(), other.attrId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.attrName)) {
        this.attrName = data().deepCopy(fields()[1].schema(), other.attrName);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.dataTypePhysical)) {
        this.dataTypePhysical = data().deepCopy(fields()[2].schema(), other.dataTypePhysical);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.relation)) {
        this.relation = data().deepCopy(fields()[3].schema(), other.relation);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.value)) {
        this.value = data().deepCopy(fields()[4].schema(), other.value);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.measure)) {
        this.measure = data().deepCopy(fields()[5].schema(), other.measure);
        fieldSetFlags()[5] = true;
      }
      this.measureBuilder = null;
      if (isValidValue(fields()[6], other.addProperties)) {
        this.addProperties = data().deepCopy(fields()[6].schema(), other.addProperties);
        fieldSetFlags()[6] = true;
      }
    }

    /**
      * Gets the value of the 'attrId' field.
      * Guid качественной характеристики
      * @return The value.
      */
    public java.lang.CharSequence getAttrId() {
      return attrId;
    }


    /**
      * Sets the value of the 'attrId' field.
      * Guid качественной характеристики
      * @param value The value of 'attrId'.
      * @return This builder.
      */
    public nlmk.mes.cgp.asap.adapter.analysis.request.v0.RecordQualityIndicators.Builder setAttrId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.attrId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'attrId' field has been set.
      * Guid качественной характеристики
      * @return True if the 'attrId' field has been set, false otherwise.
      */
    public boolean hasAttrId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'attrId' field.
      * Guid качественной характеристики
      * @return This builder.
      */
    public nlmk.mes.cgp.asap.adapter.analysis.request.v0.RecordQualityIndicators.Builder clearAttrId() {
      attrId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'attrName' field.
      * Наименование качественной характеристики
      * @return The value.
      */
    public java.lang.CharSequence getAttrName() {
      return attrName;
    }


    /**
      * Sets the value of the 'attrName' field.
      * Наименование качественной характеристики
      * @param value The value of 'attrName'.
      * @return This builder.
      */
    public nlmk.mes.cgp.asap.adapter.analysis.request.v0.RecordQualityIndicators.Builder setAttrName(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.attrName = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'attrName' field has been set.
      * Наименование качественной характеристики
      * @return True if the 'attrName' field has been set, false otherwise.
      */
    public boolean hasAttrName() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'attrName' field.
      * Наименование качественной характеристики
      * @return This builder.
      */
    public nlmk.mes.cgp.asap.adapter.analysis.request.v0.RecordQualityIndicators.Builder clearAttrName() {
      attrName = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'dataTypePhysical' field.
      * Константа обозначения физического типа AVRO
      * @return The value.
      */
    public java.lang.CharSequence getDataTypePhysical() {
      return dataTypePhysical;
    }


    /**
      * Sets the value of the 'dataTypePhysical' field.
      * Константа обозначения физического типа AVRO
      * @param value The value of 'dataTypePhysical'.
      * @return This builder.
      */
    public nlmk.mes.cgp.asap.adapter.analysis.request.v0.RecordQualityIndicators.Builder setDataTypePhysical(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.dataTypePhysical = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'dataTypePhysical' field has been set.
      * Константа обозначения физического типа AVRO
      * @return True if the 'dataTypePhysical' field has been set, false otherwise.
      */
    public boolean hasDataTypePhysical() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'dataTypePhysical' field.
      * Константа обозначения физического типа AVRO
      * @return This builder.
      */
    public nlmk.mes.cgp.asap.adapter.analysis.request.v0.RecordQualityIndicators.Builder clearDataTypePhysical() {
      dataTypePhysical = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'relation' field.
      * @return The value.
      */
    public nlmk.mes.cgp.asap.adapter.analysis.request.v0.Relation getRelation() {
      return relation;
    }


    /**
      * Sets the value of the 'relation' field.
      * @param value The value of 'relation'.
      * @return This builder.
      */
    public nlmk.mes.cgp.asap.adapter.analysis.request.v0.RecordQualityIndicators.Builder setRelation(nlmk.mes.cgp.asap.adapter.analysis.request.v0.Relation value) {
      validate(fields()[3], value);
      this.relation = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'relation' field has been set.
      * @return True if the 'relation' field has been set, false otherwise.
      */
    public boolean hasRelation() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'relation' field.
      * @return This builder.
      */
    public nlmk.mes.cgp.asap.adapter.analysis.request.v0.RecordQualityIndicators.Builder clearRelation() {
      relation = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'value' field.
      * Значение качественной характеристики
      * @return The value.
      */
    public java.lang.CharSequence getValue() {
      return value;
    }


    /**
      * Sets the value of the 'value' field.
      * Значение качественной характеристики
      * @param value The value of 'value'.
      * @return This builder.
      */
    public nlmk.mes.cgp.asap.adapter.analysis.request.v0.RecordQualityIndicators.Builder setValue(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.value = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'value' field has been set.
      * Значение качественной характеристики
      * @return True if the 'value' field has been set, false otherwise.
      */
    public boolean hasValue() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'value' field.
      * Значение качественной характеристики
      * @return This builder.
      */
    public nlmk.mes.cgp.asap.adapter.analysis.request.v0.RecordQualityIndicators.Builder clearValue() {
      value = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'measure' field.
      * @return The value.
      */
    public nlmk.mes.cgp.asap.adapter.analysis.request.v0.RecordMeasure getMeasure() {
      return measure;
    }


    /**
      * Sets the value of the 'measure' field.
      * @param value The value of 'measure'.
      * @return This builder.
      */
    public nlmk.mes.cgp.asap.adapter.analysis.request.v0.RecordQualityIndicators.Builder setMeasure(nlmk.mes.cgp.asap.adapter.analysis.request.v0.RecordMeasure value) {
      validate(fields()[5], value);
      this.measureBuilder = null;
      this.measure = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'measure' field has been set.
      * @return True if the 'measure' field has been set, false otherwise.
      */
    public boolean hasMeasure() {
      return fieldSetFlags()[5];
    }

    /**
     * Gets the Builder instance for the 'measure' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public nlmk.mes.cgp.asap.adapter.analysis.request.v0.RecordMeasure.Builder getMeasureBuilder() {
      if (measureBuilder == null) {
        if (hasMeasure()) {
          setMeasureBuilder(nlmk.mes.cgp.asap.adapter.analysis.request.v0.RecordMeasure.newBuilder(measure));
        } else {
          setMeasureBuilder(nlmk.mes.cgp.asap.adapter.analysis.request.v0.RecordMeasure.newBuilder());
        }
      }
      return measureBuilder;
    }

    /**
     * Sets the Builder instance for the 'measure' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */

    public nlmk.mes.cgp.asap.adapter.analysis.request.v0.RecordQualityIndicators.Builder setMeasureBuilder(nlmk.mes.cgp.asap.adapter.analysis.request.v0.RecordMeasure.Builder value) {
      clearMeasure();
      measureBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'measure' field has an active Builder instance
     * @return True if the 'measure' field has an active Builder instance
     */
    public boolean hasMeasureBuilder() {
      return measureBuilder != null;
    }

    /**
      * Clears the value of the 'measure' field.
      * @return This builder.
      */
    public nlmk.mes.cgp.asap.adapter.analysis.request.v0.RecordQualityIndicators.Builder clearMeasure() {
      measure = null;
      measureBuilder = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'addProperties' field.
      * @return The value.
      */
    public java.util.List<nlmk.mes.cgp.asap.adapter.analysis.request.v0.RecordAddProperties> getAddProperties() {
      return addProperties;
    }


    /**
      * Sets the value of the 'addProperties' field.
      * @param value The value of 'addProperties'.
      * @return This builder.
      */
    public nlmk.mes.cgp.asap.adapter.analysis.request.v0.RecordQualityIndicators.Builder setAddProperties(java.util.List<nlmk.mes.cgp.asap.adapter.analysis.request.v0.RecordAddProperties> value) {
      validate(fields()[6], value);
      this.addProperties = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'addProperties' field has been set.
      * @return True if the 'addProperties' field has been set, false otherwise.
      */
    public boolean hasAddProperties() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'addProperties' field.
      * @return This builder.
      */
    public nlmk.mes.cgp.asap.adapter.analysis.request.v0.RecordQualityIndicators.Builder clearAddProperties() {
      addProperties = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public RecordQualityIndicators build() {
      try {
        RecordQualityIndicators record = new RecordQualityIndicators();
        record.attrId = fieldSetFlags()[0] ? this.attrId : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.attrName = fieldSetFlags()[1] ? this.attrName : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.dataTypePhysical = fieldSetFlags()[2] ? this.dataTypePhysical : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.relation = fieldSetFlags()[3] ? this.relation : (nlmk.mes.cgp.asap.adapter.analysis.request.v0.Relation) defaultValue(fields()[3]);
        record.value = fieldSetFlags()[4] ? this.value : (java.lang.CharSequence) defaultValue(fields()[4]);
        if (measureBuilder != null) {
          try {
            record.measure = this.measureBuilder.build();
          } catch (org.apache.avro.AvroMissingFieldException e) {
            e.addParentField(record.getSchema().getField("measure"));
            throw e;
          }
        } else {
          record.measure = fieldSetFlags()[5] ? this.measure : (nlmk.mes.cgp.asap.adapter.analysis.request.v0.RecordMeasure) defaultValue(fields()[5]);
        }
        record.addProperties = fieldSetFlags()[6] ? this.addProperties : (java.util.List<nlmk.mes.cgp.asap.adapter.analysis.request.v0.RecordAddProperties>) defaultValue(fields()[6]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<RecordQualityIndicators>
    WRITER$ = (org.apache.avro.io.DatumWriter<RecordQualityIndicators>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<RecordQualityIndicators>
    READER$ = (org.apache.avro.io.DatumReader<RecordQualityIndicators>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.attrId);

    out.writeString(this.attrName);

    out.writeString(this.dataTypePhysical);

    out.writeEnum(this.relation.ordinal());

    out.writeString(this.value);

    if (this.measure == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      this.measure.customEncode(out);
    }

    if (this.addProperties == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      long size0 = this.addProperties.size();
      out.writeArrayStart();
      out.setItemCount(size0);
      long actualSize0 = 0;
      for (nlmk.mes.cgp.asap.adapter.analysis.request.v0.RecordAddProperties e0: this.addProperties) {
        actualSize0++;
        out.startItem();
        e0.customEncode(out);
      }
      out.writeArrayEnd();
      if (actualSize0 != size0)
        throw new java.util.ConcurrentModificationException("Array-size written was " + size0 + ", but element count was " + actualSize0 + ".");
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.attrId = in.readString(this.attrId instanceof Utf8 ? (Utf8)this.attrId : null);

      this.attrName = in.readString(this.attrName instanceof Utf8 ? (Utf8)this.attrName : null);

      this.dataTypePhysical = in.readString(this.dataTypePhysical instanceof Utf8 ? (Utf8)this.dataTypePhysical : null);

      this.relation = nlmk.mes.cgp.asap.adapter.analysis.request.v0.Relation.values()[in.readEnum()];

      this.value = in.readString(this.value instanceof Utf8 ? (Utf8)this.value : null);

      if (in.readIndex() != 1) {
        in.readNull();
        this.measure = null;
      } else {
        if (this.measure == null) {
          this.measure = new nlmk.mes.cgp.asap.adapter.analysis.request.v0.RecordMeasure();
        }
        this.measure.customDecode(in);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.addProperties = null;
      } else {
        long size0 = in.readArrayStart();
        java.util.List<nlmk.mes.cgp.asap.adapter.analysis.request.v0.RecordAddProperties> a0 = this.addProperties;
        if (a0 == null) {
          a0 = new SpecificData.Array<nlmk.mes.cgp.asap.adapter.analysis.request.v0.RecordAddProperties>((int)size0, SCHEMA$.getField("addProperties").schema().getTypes().get(1));
          this.addProperties = a0;
        } else a0.clear();
        SpecificData.Array<nlmk.mes.cgp.asap.adapter.analysis.request.v0.RecordAddProperties> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<nlmk.mes.cgp.asap.adapter.analysis.request.v0.RecordAddProperties>)a0 : null);
        for ( ; 0 < size0; size0 = in.arrayNext()) {
          for ( ; size0 != 0; size0--) {
            nlmk.mes.cgp.asap.adapter.analysis.request.v0.RecordAddProperties e0 = (ga0 != null ? ga0.peek() : null);
            if (e0 == null) {
              e0 = new nlmk.mes.cgp.asap.adapter.analysis.request.v0.RecordAddProperties();
            }
            e0.customDecode(in);
            a0.add(e0);
          }
        }
      }

    } else {
      for (int i = 0; i < 7; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.attrId = in.readString(this.attrId instanceof Utf8 ? (Utf8)this.attrId : null);
          break;

        case 1:
          this.attrName = in.readString(this.attrName instanceof Utf8 ? (Utf8)this.attrName : null);
          break;

        case 2:
          this.dataTypePhysical = in.readString(this.dataTypePhysical instanceof Utf8 ? (Utf8)this.dataTypePhysical : null);
          break;

        case 3:
          this.relation = nlmk.mes.cgp.asap.adapter.analysis.request.v0.Relation.values()[in.readEnum()];
          break;

        case 4:
          this.value = in.readString(this.value instanceof Utf8 ? (Utf8)this.value : null);
          break;

        case 5:
          if (in.readIndex() != 1) {
            in.readNull();
            this.measure = null;
          } else {
            if (this.measure == null) {
              this.measure = new nlmk.mes.cgp.asap.adapter.analysis.request.v0.RecordMeasure();
            }
            this.measure.customDecode(in);
          }
          break;

        case 6:
          if (in.readIndex() != 1) {
            in.readNull();
            this.addProperties = null;
          } else {
            long size0 = in.readArrayStart();
            java.util.List<nlmk.mes.cgp.asap.adapter.analysis.request.v0.RecordAddProperties> a0 = this.addProperties;
            if (a0 == null) {
              a0 = new SpecificData.Array<nlmk.mes.cgp.asap.adapter.analysis.request.v0.RecordAddProperties>((int)size0, SCHEMA$.getField("addProperties").schema().getTypes().get(1));
              this.addProperties = a0;
            } else a0.clear();
            SpecificData.Array<nlmk.mes.cgp.asap.adapter.analysis.request.v0.RecordAddProperties> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<nlmk.mes.cgp.asap.adapter.analysis.request.v0.RecordAddProperties>)a0 : null);
            for ( ; 0 < size0; size0 = in.arrayNext()) {
              for ( ; size0 != 0; size0--) {
                nlmk.mes.cgp.asap.adapter.analysis.request.v0.RecordAddProperties e0 = (ga0 != null ? ga0.peek() : null);
                if (e0 == null) {
                  e0 = new nlmk.mes.cgp.asap.adapter.analysis.request.v0.RecordAddProperties();
                }
                e0.customDecode(in);
                a0.add(e0);
              }
            }
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










