/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package nlmk.mes.cgp.asap.adapter.analysis.request.v0;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

/** Единица измерения */
@org.apache.avro.specific.AvroGenerated
public class RecordMeasureProperties extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -5837159065291940965L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"RecordMeasureProperties\",\"namespace\":\"nlmk.mes.cgp.asap.adapter.analysis.request.v0\",\"doc\":\"Единица измерения\",\"fields\":[{\"name\":\"measureId\",\"type\":\"string\",\"doc\":\"Guid единицы измерения\"},{\"name\":\"measureName\",\"type\":\"string\",\"doc\":\"Наименование единицы измерения\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<RecordMeasureProperties> ENCODER =
      new BinaryMessageEncoder<RecordMeasureProperties>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<RecordMeasureProperties> DECODER =
      new BinaryMessageDecoder<RecordMeasureProperties>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<RecordMeasureProperties> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<RecordMeasureProperties> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<RecordMeasureProperties> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<RecordMeasureProperties>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this RecordMeasureProperties to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a RecordMeasureProperties from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a RecordMeasureProperties instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static RecordMeasureProperties fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** Guid единицы измерения */
   private java.lang.CharSequence measureId;
  /** Наименование единицы измерения */
   private java.lang.CharSequence measureName;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public RecordMeasureProperties() {}

  /**
   * All-args constructor.
   * @param measureId Guid единицы измерения
   * @param measureName Наименование единицы измерения
   */
  public RecordMeasureProperties(java.lang.CharSequence measureId, java.lang.CharSequence measureName) {
    this.measureId = measureId;
    this.measureName = measureName;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return measureId;
    case 1: return measureName;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: measureId = (java.lang.CharSequence)value$; break;
    case 1: measureName = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'measureId' field.
   * @return Guid единицы измерения
   */
  public java.lang.CharSequence getMeasureId() {
    return measureId;
  }


  /**
   * Sets the value of the 'measureId' field.
   * Guid единицы измерения
   * @param value the value to set.
   */
  public void setMeasureId(java.lang.CharSequence value) {
    this.measureId = value;
  }

  /**
   * Gets the value of the 'measureName' field.
   * @return Наименование единицы измерения
   */
  public java.lang.CharSequence getMeasureName() {
    return measureName;
  }


  /**
   * Sets the value of the 'measureName' field.
   * Наименование единицы измерения
   * @param value the value to set.
   */
  public void setMeasureName(java.lang.CharSequence value) {
    this.measureName = value;
  }

  /**
   * Creates a new RecordMeasureProperties RecordBuilder.
   * @return A new RecordMeasureProperties RecordBuilder
   */
  public static nlmk.mes.cgp.asap.adapter.analysis.request.v0.RecordMeasureProperties.Builder newBuilder() {
    return new nlmk.mes.cgp.asap.adapter.analysis.request.v0.RecordMeasureProperties.Builder();
  }

  /**
   * Creates a new RecordMeasureProperties RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new RecordMeasureProperties RecordBuilder
   */
  public static nlmk.mes.cgp.asap.adapter.analysis.request.v0.RecordMeasureProperties.Builder newBuilder(nlmk.mes.cgp.asap.adapter.analysis.request.v0.RecordMeasureProperties.Builder other) {
    if (other == null) {
      return new nlmk.mes.cgp.asap.adapter.analysis.request.v0.RecordMeasureProperties.Builder();
    } else {
      return new nlmk.mes.cgp.asap.adapter.analysis.request.v0.RecordMeasureProperties.Builder(other);
    }
  }

  /**
   * Creates a new RecordMeasureProperties RecordBuilder by copying an existing RecordMeasureProperties instance.
   * @param other The existing instance to copy.
   * @return A new RecordMeasureProperties RecordBuilder
   */
  public static nlmk.mes.cgp.asap.adapter.analysis.request.v0.RecordMeasureProperties.Builder newBuilder(nlmk.mes.cgp.asap.adapter.analysis.request.v0.RecordMeasureProperties other) {
    if (other == null) {
      return new nlmk.mes.cgp.asap.adapter.analysis.request.v0.RecordMeasureProperties.Builder();
    } else {
      return new nlmk.mes.cgp.asap.adapter.analysis.request.v0.RecordMeasureProperties.Builder(other);
    }
  }

  /**
   * RecordBuilder for RecordMeasureProperties instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<RecordMeasureProperties>
    implements org.apache.avro.data.RecordBuilder<RecordMeasureProperties> {

    /** Guid единицы измерения */
    private java.lang.CharSequence measureId;
    /** Наименование единицы измерения */
    private java.lang.CharSequence measureName;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(nlmk.mes.cgp.asap.adapter.analysis.request.v0.RecordMeasureProperties.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.measureId)) {
        this.measureId = data().deepCopy(fields()[0].schema(), other.measureId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.measureName)) {
        this.measureName = data().deepCopy(fields()[1].schema(), other.measureName);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing RecordMeasureProperties instance
     * @param other The existing instance to copy.
     */
    private Builder(nlmk.mes.cgp.asap.adapter.analysis.request.v0.RecordMeasureProperties other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.measureId)) {
        this.measureId = data().deepCopy(fields()[0].schema(), other.measureId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.measureName)) {
        this.measureName = data().deepCopy(fields()[1].schema(), other.measureName);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'measureId' field.
      * Guid единицы измерения
      * @return The value.
      */
    public java.lang.CharSequence getMeasureId() {
      return measureId;
    }


    /**
      * Sets the value of the 'measureId' field.
      * Guid единицы измерения
      * @param value The value of 'measureId'.
      * @return This builder.
      */
    public nlmk.mes.cgp.asap.adapter.analysis.request.v0.RecordMeasureProperties.Builder setMeasureId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.measureId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'measureId' field has been set.
      * Guid единицы измерения
      * @return True if the 'measureId' field has been set, false otherwise.
      */
    public boolean hasMeasureId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'measureId' field.
      * Guid единицы измерения
      * @return This builder.
      */
    public nlmk.mes.cgp.asap.adapter.analysis.request.v0.RecordMeasureProperties.Builder clearMeasureId() {
      measureId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'measureName' field.
      * Наименование единицы измерения
      * @return The value.
      */
    public java.lang.CharSequence getMeasureName() {
      return measureName;
    }


    /**
      * Sets the value of the 'measureName' field.
      * Наименование единицы измерения
      * @param value The value of 'measureName'.
      * @return This builder.
      */
    public nlmk.mes.cgp.asap.adapter.analysis.request.v0.RecordMeasureProperties.Builder setMeasureName(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.measureName = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'measureName' field has been set.
      * Наименование единицы измерения
      * @return True if the 'measureName' field has been set, false otherwise.
      */
    public boolean hasMeasureName() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'measureName' field.
      * Наименование единицы измерения
      * @return This builder.
      */
    public nlmk.mes.cgp.asap.adapter.analysis.request.v0.RecordMeasureProperties.Builder clearMeasureName() {
      measureName = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public RecordMeasureProperties build() {
      try {
        RecordMeasureProperties record = new RecordMeasureProperties();
        record.measureId = fieldSetFlags()[0] ? this.measureId : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.measureName = fieldSetFlags()[1] ? this.measureName : (java.lang.CharSequence) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<RecordMeasureProperties>
    WRITER$ = (org.apache.avro.io.DatumWriter<RecordMeasureProperties>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<RecordMeasureProperties>
    READER$ = (org.apache.avro.io.DatumReader<RecordMeasureProperties>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.measureId);

    out.writeString(this.measureName);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.measureId = in.readString(this.measureId instanceof Utf8 ? (Utf8)this.measureId : null);

      this.measureName = in.readString(this.measureName instanceof Utf8 ? (Utf8)this.measureName : null);

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.measureId = in.readString(this.measureId instanceof Utf8 ? (Utf8)this.measureId : null);
          break;

        case 1:
          this.measureName = in.readString(this.measureName instanceof Utf8 ? (Utf8)this.measureName : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










