/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package nlmk.mes.cgp.asap.adapter.analysis.request.v0;
/** Оператор сравнения */
@org.apache.avro.specific.AvroGenerated
public enum Relation implements org.apache.avro.generic.GenericEnumSymbol<Relation> {
  EQUAL, MORE, LESS  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"Relation\",\"namespace\":\"nlmk.mes.cgp.asap.adapter.analysis.request.v0\",\"doc\":\"Оператор сравнения\",\"symbols\":[\"EQUAL\",\"MORE\",\"LESS\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
