/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package nlmk.mes.cgp.asap.adapter.analysis.request.v0;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class Sys extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -1500240813746548028L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Sys\",\"namespace\":\"nlmk.mes.cgp.asap.adapter.analysis.request.v0\",\"fields\":[{\"name\":\"seqID\",\"type\":\"long\",\"doc\":\"Монотонно возрастающий счетчик для проверки или восстановления оригинальной последовательности\",\"default\":-1},{\"name\":\"traceID\",\"type\":\"string\",\"doc\":\"Сквозной Trace ID (обычно UUID)\",\"default\":\"\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Sys> ENCODER =
      new BinaryMessageEncoder<Sys>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Sys> DECODER =
      new BinaryMessageDecoder<Sys>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Sys> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Sys> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Sys> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Sys>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Sys to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Sys from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Sys instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Sys fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** Монотонно возрастающий счетчик для проверки или восстановления оригинальной последовательности */
   private long seqID;
  /** Сквозной Trace ID (обычно UUID) */
   private java.lang.CharSequence traceID;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Sys() {}

  /**
   * All-args constructor.
   * @param seqID Монотонно возрастающий счетчик для проверки или восстановления оригинальной последовательности
   * @param traceID Сквозной Trace ID (обычно UUID)
   */
  public Sys(java.lang.Long seqID, java.lang.CharSequence traceID) {
    this.seqID = seqID;
    this.traceID = traceID;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return seqID;
    case 1: return traceID;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: seqID = (java.lang.Long)value$; break;
    case 1: traceID = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'seqID' field.
   * @return Монотонно возрастающий счетчик для проверки или восстановления оригинальной последовательности
   */
  public long getSeqID() {
    return seqID;
  }


  /**
   * Sets the value of the 'seqID' field.
   * Монотонно возрастающий счетчик для проверки или восстановления оригинальной последовательности
   * @param value the value to set.
   */
  public void setSeqID(long value) {
    this.seqID = value;
  }

  /**
   * Gets the value of the 'traceID' field.
   * @return Сквозной Trace ID (обычно UUID)
   */
  public java.lang.CharSequence getTraceID() {
    return traceID;
  }


  /**
   * Sets the value of the 'traceID' field.
   * Сквозной Trace ID (обычно UUID)
   * @param value the value to set.
   */
  public void setTraceID(java.lang.CharSequence value) {
    this.traceID = value;
  }

  /**
   * Creates a new Sys RecordBuilder.
   * @return A new Sys RecordBuilder
   */
  public static nlmk.mes.cgp.asap.adapter.analysis.request.v0.Sys.Builder newBuilder() {
    return new nlmk.mes.cgp.asap.adapter.analysis.request.v0.Sys.Builder();
  }

  /**
   * Creates a new Sys RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Sys RecordBuilder
   */
  public static nlmk.mes.cgp.asap.adapter.analysis.request.v0.Sys.Builder newBuilder(nlmk.mes.cgp.asap.adapter.analysis.request.v0.Sys.Builder other) {
    if (other == null) {
      return new nlmk.mes.cgp.asap.adapter.analysis.request.v0.Sys.Builder();
    } else {
      return new nlmk.mes.cgp.asap.adapter.analysis.request.v0.Sys.Builder(other);
    }
  }

  /**
   * Creates a new Sys RecordBuilder by copying an existing Sys instance.
   * @param other The existing instance to copy.
   * @return A new Sys RecordBuilder
   */
  public static nlmk.mes.cgp.asap.adapter.analysis.request.v0.Sys.Builder newBuilder(nlmk.mes.cgp.asap.adapter.analysis.request.v0.Sys other) {
    if (other == null) {
      return new nlmk.mes.cgp.asap.adapter.analysis.request.v0.Sys.Builder();
    } else {
      return new nlmk.mes.cgp.asap.adapter.analysis.request.v0.Sys.Builder(other);
    }
  }

  /**
   * RecordBuilder for Sys instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Sys>
    implements org.apache.avro.data.RecordBuilder<Sys> {

    /** Монотонно возрастающий счетчик для проверки или восстановления оригинальной последовательности */
    private long seqID;
    /** Сквозной Trace ID (обычно UUID) */
    private java.lang.CharSequence traceID;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(nlmk.mes.cgp.asap.adapter.analysis.request.v0.Sys.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.seqID)) {
        this.seqID = data().deepCopy(fields()[0].schema(), other.seqID);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.traceID)) {
        this.traceID = data().deepCopy(fields()[1].schema(), other.traceID);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing Sys instance
     * @param other The existing instance to copy.
     */
    private Builder(nlmk.mes.cgp.asap.adapter.analysis.request.v0.Sys other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.seqID)) {
        this.seqID = data().deepCopy(fields()[0].schema(), other.seqID);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.traceID)) {
        this.traceID = data().deepCopy(fields()[1].schema(), other.traceID);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'seqID' field.
      * Монотонно возрастающий счетчик для проверки или восстановления оригинальной последовательности
      * @return The value.
      */
    public long getSeqID() {
      return seqID;
    }


    /**
      * Sets the value of the 'seqID' field.
      * Монотонно возрастающий счетчик для проверки или восстановления оригинальной последовательности
      * @param value The value of 'seqID'.
      * @return This builder.
      */
    public nlmk.mes.cgp.asap.adapter.analysis.request.v0.Sys.Builder setSeqID(long value) {
      validate(fields()[0], value);
      this.seqID = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'seqID' field has been set.
      * Монотонно возрастающий счетчик для проверки или восстановления оригинальной последовательности
      * @return True if the 'seqID' field has been set, false otherwise.
      */
    public boolean hasSeqID() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'seqID' field.
      * Монотонно возрастающий счетчик для проверки или восстановления оригинальной последовательности
      * @return This builder.
      */
    public nlmk.mes.cgp.asap.adapter.analysis.request.v0.Sys.Builder clearSeqID() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'traceID' field.
      * Сквозной Trace ID (обычно UUID)
      * @return The value.
      */
    public java.lang.CharSequence getTraceID() {
      return traceID;
    }


    /**
      * Sets the value of the 'traceID' field.
      * Сквозной Trace ID (обычно UUID)
      * @param value The value of 'traceID'.
      * @return This builder.
      */
    public nlmk.mes.cgp.asap.adapter.analysis.request.v0.Sys.Builder setTraceID(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.traceID = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'traceID' field has been set.
      * Сквозной Trace ID (обычно UUID)
      * @return True if the 'traceID' field has been set, false otherwise.
      */
    public boolean hasTraceID() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'traceID' field.
      * Сквозной Trace ID (обычно UUID)
      * @return This builder.
      */
    public nlmk.mes.cgp.asap.adapter.analysis.request.v0.Sys.Builder clearTraceID() {
      traceID = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Sys build() {
      try {
        Sys record = new Sys();
        record.seqID = fieldSetFlags()[0] ? this.seqID : (java.lang.Long) defaultValue(fields()[0]);
        record.traceID = fieldSetFlags()[1] ? this.traceID : (java.lang.CharSequence) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Sys>
    WRITER$ = (org.apache.avro.io.DatumWriter<Sys>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Sys>
    READER$ = (org.apache.avro.io.DatumReader<Sys>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeLong(this.seqID);

    out.writeString(this.traceID);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.seqID = in.readLong();

      this.traceID = in.readString(this.traceID instanceof Utf8 ? (Utf8)this.traceID : null);

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.seqID = in.readLong();
          break;

        case 1:
          this.traceID = in.readString(this.traceID instanceof Utf8 ? (Utf8)this.traceID : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










