/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package nlmk.l3.apcs;
@org.apache.avro.specific.AvroGenerated
public enum EnumOp implements org.apache.avro.generic.GenericEnumSymbol<EnumOp> {
  I, U  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"EnumOp\",\"namespace\":\"nlmk.l3.apcs\",\"symbols\":[\"I\",\"U\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
