/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package nlmk.l3.apcs;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class NormSpecData extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -3195275700524147889L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"NormSpecData\",\"namespace\":\"nlmk.l3.apcs\",\"fields\":[{\"name\":\"listAccValues\",\"type\":[\"null\",{\"type\":\"array\",\"items\":\"string\"}],\"default\":null},{\"name\":\"valueMin\",\"type\":[\"null\",\"int\"],\"doc\":\"Минимальное допустимое значение\",\"default\":null},{\"name\":\"valueMax\",\"type\":[\"null\",\"int\"],\"doc\":\"Максимальное допустимое значение\",\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<NormSpecData> ENCODER =
      new BinaryMessageEncoder<NormSpecData>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<NormSpecData> DECODER =
      new BinaryMessageDecoder<NormSpecData>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<NormSpecData> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<NormSpecData> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<NormSpecData> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<NormSpecData>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this NormSpecData to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a NormSpecData from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a NormSpecData instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static NormSpecData fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.util.List<java.lang.CharSequence> listAccValues;
  /** Минимальное допустимое значение */
   private java.lang.Integer valueMin;
  /** Максимальное допустимое значение */
   private java.lang.Integer valueMax;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public NormSpecData() {}

  /**
   * All-args constructor.
   * @param listAccValues The new value for listAccValues
   * @param valueMin Минимальное допустимое значение
   * @param valueMax Максимальное допустимое значение
   */
  public NormSpecData(java.util.List<java.lang.CharSequence> listAccValues, java.lang.Integer valueMin, java.lang.Integer valueMax) {
    this.listAccValues = listAccValues;
    this.valueMin = valueMin;
    this.valueMax = valueMax;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return listAccValues;
    case 1: return valueMin;
    case 2: return valueMax;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: listAccValues = (java.util.List<java.lang.CharSequence>)value$; break;
    case 1: valueMin = (java.lang.Integer)value$; break;
    case 2: valueMax = (java.lang.Integer)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'listAccValues' field.
   * @return The value of the 'listAccValues' field.
   */
  public java.util.List<java.lang.CharSequence> getListAccValues() {
    return listAccValues;
  }


  /**
   * Sets the value of the 'listAccValues' field.
   * @param value the value to set.
   */
  public void setListAccValues(java.util.List<java.lang.CharSequence> value) {
    this.listAccValues = value;
  }

  /**
   * Gets the value of the 'valueMin' field.
   * @return Минимальное допустимое значение
   */
  public java.lang.Integer getValueMin() {
    return valueMin;
  }


  /**
   * Sets the value of the 'valueMin' field.
   * Минимальное допустимое значение
   * @param value the value to set.
   */
  public void setValueMin(java.lang.Integer value) {
    this.valueMin = value;
  }

  /**
   * Gets the value of the 'valueMax' field.
   * @return Максимальное допустимое значение
   */
  public java.lang.Integer getValueMax() {
    return valueMax;
  }


  /**
   * Sets the value of the 'valueMax' field.
   * Максимальное допустимое значение
   * @param value the value to set.
   */
  public void setValueMax(java.lang.Integer value) {
    this.valueMax = value;
  }

  /**
   * Creates a new NormSpecData RecordBuilder.
   * @return A new NormSpecData RecordBuilder
   */
  public static nlmk.l3.apcs.NormSpecData.Builder newBuilder() {
    return new nlmk.l3.apcs.NormSpecData.Builder();
  }

  /**
   * Creates a new NormSpecData RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new NormSpecData RecordBuilder
   */
  public static nlmk.l3.apcs.NormSpecData.Builder newBuilder(nlmk.l3.apcs.NormSpecData.Builder other) {
    if (other == null) {
      return new nlmk.l3.apcs.NormSpecData.Builder();
    } else {
      return new nlmk.l3.apcs.NormSpecData.Builder(other);
    }
  }

  /**
   * Creates a new NormSpecData RecordBuilder by copying an existing NormSpecData instance.
   * @param other The existing instance to copy.
   * @return A new NormSpecData RecordBuilder
   */
  public static nlmk.l3.apcs.NormSpecData.Builder newBuilder(nlmk.l3.apcs.NormSpecData other) {
    if (other == null) {
      return new nlmk.l3.apcs.NormSpecData.Builder();
    } else {
      return new nlmk.l3.apcs.NormSpecData.Builder(other);
    }
  }

  /**
   * RecordBuilder for NormSpecData instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<NormSpecData>
    implements org.apache.avro.data.RecordBuilder<NormSpecData> {

    private java.util.List<java.lang.CharSequence> listAccValues;
    /** Минимальное допустимое значение */
    private java.lang.Integer valueMin;
    /** Максимальное допустимое значение */
    private java.lang.Integer valueMax;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(nlmk.l3.apcs.NormSpecData.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.listAccValues)) {
        this.listAccValues = data().deepCopy(fields()[0].schema(), other.listAccValues);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.valueMin)) {
        this.valueMin = data().deepCopy(fields()[1].schema(), other.valueMin);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.valueMax)) {
        this.valueMax = data().deepCopy(fields()[2].schema(), other.valueMax);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing NormSpecData instance
     * @param other The existing instance to copy.
     */
    private Builder(nlmk.l3.apcs.NormSpecData other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.listAccValues)) {
        this.listAccValues = data().deepCopy(fields()[0].schema(), other.listAccValues);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.valueMin)) {
        this.valueMin = data().deepCopy(fields()[1].schema(), other.valueMin);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.valueMax)) {
        this.valueMax = data().deepCopy(fields()[2].schema(), other.valueMax);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'listAccValues' field.
      * @return The value.
      */
    public java.util.List<java.lang.CharSequence> getListAccValues() {
      return listAccValues;
    }


    /**
      * Sets the value of the 'listAccValues' field.
      * @param value The value of 'listAccValues'.
      * @return This builder.
      */
    public nlmk.l3.apcs.NormSpecData.Builder setListAccValues(java.util.List<java.lang.CharSequence> value) {
      validate(fields()[0], value);
      this.listAccValues = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'listAccValues' field has been set.
      * @return True if the 'listAccValues' field has been set, false otherwise.
      */
    public boolean hasListAccValues() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'listAccValues' field.
      * @return This builder.
      */
    public nlmk.l3.apcs.NormSpecData.Builder clearListAccValues() {
      listAccValues = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'valueMin' field.
      * Минимальное допустимое значение
      * @return The value.
      */
    public java.lang.Integer getValueMin() {
      return valueMin;
    }


    /**
      * Sets the value of the 'valueMin' field.
      * Минимальное допустимое значение
      * @param value The value of 'valueMin'.
      * @return This builder.
      */
    public nlmk.l3.apcs.NormSpecData.Builder setValueMin(java.lang.Integer value) {
      validate(fields()[1], value);
      this.valueMin = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'valueMin' field has been set.
      * Минимальное допустимое значение
      * @return True if the 'valueMin' field has been set, false otherwise.
      */
    public boolean hasValueMin() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'valueMin' field.
      * Минимальное допустимое значение
      * @return This builder.
      */
    public nlmk.l3.apcs.NormSpecData.Builder clearValueMin() {
      valueMin = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'valueMax' field.
      * Максимальное допустимое значение
      * @return The value.
      */
    public java.lang.Integer getValueMax() {
      return valueMax;
    }


    /**
      * Sets the value of the 'valueMax' field.
      * Максимальное допустимое значение
      * @param value The value of 'valueMax'.
      * @return This builder.
      */
    public nlmk.l3.apcs.NormSpecData.Builder setValueMax(java.lang.Integer value) {
      validate(fields()[2], value);
      this.valueMax = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'valueMax' field has been set.
      * Максимальное допустимое значение
      * @return True if the 'valueMax' field has been set, false otherwise.
      */
    public boolean hasValueMax() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'valueMax' field.
      * Максимальное допустимое значение
      * @return This builder.
      */
    public nlmk.l3.apcs.NormSpecData.Builder clearValueMax() {
      valueMax = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public NormSpecData build() {
      try {
        NormSpecData record = new NormSpecData();
        record.listAccValues = fieldSetFlags()[0] ? this.listAccValues : (java.util.List<java.lang.CharSequence>) defaultValue(fields()[0]);
        record.valueMin = fieldSetFlags()[1] ? this.valueMin : (java.lang.Integer) defaultValue(fields()[1]);
        record.valueMax = fieldSetFlags()[2] ? this.valueMax : (java.lang.Integer) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<NormSpecData>
    WRITER$ = (org.apache.avro.io.DatumWriter<NormSpecData>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<NormSpecData>
    READER$ = (org.apache.avro.io.DatumReader<NormSpecData>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    if (this.listAccValues == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      long size0 = this.listAccValues.size();
      out.writeArrayStart();
      out.setItemCount(size0);
      long actualSize0 = 0;
      for (java.lang.CharSequence e0: this.listAccValues) {
        actualSize0++;
        out.startItem();
        out.writeString(e0);
      }
      out.writeArrayEnd();
      if (actualSize0 != size0)
        throw new java.util.ConcurrentModificationException("Array-size written was " + size0 + ", but element count was " + actualSize0 + ".");
    }

    if (this.valueMin == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeInt(this.valueMin);
    }

    if (this.valueMax == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeInt(this.valueMax);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      if (in.readIndex() != 1) {
        in.readNull();
        this.listAccValues = null;
      } else {
        long size0 = in.readArrayStart();
        java.util.List<java.lang.CharSequence> a0 = this.listAccValues;
        if (a0 == null) {
          a0 = new SpecificData.Array<java.lang.CharSequence>((int)size0, SCHEMA$.getField("listAccValues").schema().getTypes().get(1));
          this.listAccValues = a0;
        } else a0.clear();
        SpecificData.Array<java.lang.CharSequence> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<java.lang.CharSequence>)a0 : null);
        for ( ; 0 < size0; size0 = in.arrayNext()) {
          for ( ; size0 != 0; size0--) {
            java.lang.CharSequence e0 = (ga0 != null ? ga0.peek() : null);
            e0 = in.readString(e0 instanceof Utf8 ? (Utf8)e0 : null);
            a0.add(e0);
          }
        }
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.valueMin = null;
      } else {
        this.valueMin = in.readInt();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.valueMax = null;
      } else {
        this.valueMax = in.readInt();
      }

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          if (in.readIndex() != 1) {
            in.readNull();
            this.listAccValues = null;
          } else {
            long size0 = in.readArrayStart();
            java.util.List<java.lang.CharSequence> a0 = this.listAccValues;
            if (a0 == null) {
              a0 = new SpecificData.Array<java.lang.CharSequence>((int)size0, SCHEMA$.getField("listAccValues").schema().getTypes().get(1));
              this.listAccValues = a0;
            } else a0.clear();
            SpecificData.Array<java.lang.CharSequence> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<java.lang.CharSequence>)a0 : null);
            for ( ; 0 < size0; size0 = in.arrayNext()) {
              for ( ; size0 != 0; size0--) {
                java.lang.CharSequence e0 = (ga0 != null ? ga0.peek() : null);
                e0 = in.readString(e0 instanceof Utf8 ? (Utf8)e0 : null);
                a0.add(e0);
              }
            }
          }
          break;

        case 1:
          if (in.readIndex() != 1) {
            in.readNull();
            this.valueMin = null;
          } else {
            this.valueMin = in.readInt();
          }
          break;

        case 2:
          if (in.readIndex() != 1) {
            in.readNull();
            this.valueMax = null;
          } else {
            this.valueMax = in.readInt();
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










