/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package nlmk.l3.apcs;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class RecordMettallographicSpecifications extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 3024675509149533925L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"RecordMettallographicSpecifications\",\"namespace\":\"nlmk.l3.apcs\",\"fields\":[{\"name\":\"specCode\",\"type\":\"int\",\"doc\":\"Код характеристики\"},{\"name\":\"specName\",\"type\":\"string\",\"doc\":\"Наименование характеристики\"},{\"name\":\"specTypeCode\",\"type\":\"int\",\"doc\":\"Тип данных (1-строка, 2-число, 3-дата)\"},{\"name\":\"specTypeName\",\"type\":\"string\",\"doc\":\"Наименование типа данных\"},{\"name\":\"specValue\",\"type\":[\"float\",\"string\"],\"doc\":\"Значение характеристики\"},{\"name\":\"specFormat\",\"type\":[\"null\",\"string\"],\"doc\":\"Формат передачи характеристики\",\"default\":null},{\"name\":\"specMeasure\",\"type\":[\"null\",\"string\"],\"doc\":\"Единица измерения\",\"default\":null},{\"name\":\"norms\",\"type\":[\"null\",{\"type\":\"record\",\"name\":\"NormMetallData\",\"fields\":[{\"name\":\"listAccValues\",\"type\":[\"null\",{\"type\":\"array\",\"items\":\"string\"}],\"default\":null},{\"name\":\"valueMin\",\"type\":[\"null\",\"int\"],\"doc\":\"Минимальное допустимое значение\",\"default\":null},{\"name\":\"valueMax\",\"type\":[\"null\",\"int\"],\"doc\":\"Максимальное допустимое значение\",\"default\":null}]}],\"default\":null},{\"name\":\"mismatch\",\"type\":\"int\",\"doc\":\"Результаты проверки параметра 0 - не соответствует 1 - соответствует 2 - аттестация не требуется, справочное значение 3 - нет результатов испытаний, но аттестация требуется 4 - не соответствует, но есть рекомендации по устранению не соответствия 5 - соответствует, изменено сотрудником УАИП\"},{\"name\":\"note\",\"type\":[\"null\",\"string\"],\"doc\":\"Пояснение результата проверки характеристики\",\"default\":null},{\"name\":\"defectSuggestion\",\"type\":[\"null\",\"string\"],\"doc\":\"Текст рекомендации по устранению 'не соответствия'\",\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<RecordMettallographicSpecifications> ENCODER =
      new BinaryMessageEncoder<RecordMettallographicSpecifications>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<RecordMettallographicSpecifications> DECODER =
      new BinaryMessageDecoder<RecordMettallographicSpecifications>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<RecordMettallographicSpecifications> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<RecordMettallographicSpecifications> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<RecordMettallographicSpecifications> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<RecordMettallographicSpecifications>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this RecordMettallographicSpecifications to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a RecordMettallographicSpecifications from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a RecordMettallographicSpecifications instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static RecordMettallographicSpecifications fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** Код характеристики */
   private int specCode;
  /** Наименование характеристики */
   private java.lang.CharSequence specName;
  /** Тип данных (1-строка, 2-число, 3-дата) */
   private int specTypeCode;
  /** Наименование типа данных */
   private java.lang.CharSequence specTypeName;
  /** Значение характеристики */
   private java.lang.Object specValue;
  /** Формат передачи характеристики */
   private java.lang.CharSequence specFormat;
  /** Единица измерения */
   private java.lang.CharSequence specMeasure;
   private nlmk.l3.apcs.NormMetallData norms;
  /** Результаты проверки параметра 0 - не соответствует 1 - соответствует 2 - аттестация не требуется, справочное значение 3 - нет результатов испытаний, но аттестация требуется 4 - не соответствует, но есть рекомендации по устранению не соответствия 5 - соответствует, изменено сотрудником УАИП */
   private int mismatch;
  /** Пояснение результата проверки характеристики */
   private java.lang.CharSequence note;
  /** Текст рекомендации по устранению 'не соответствия' */
   private java.lang.CharSequence defectSuggestion;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public RecordMettallographicSpecifications() {}

  /**
   * All-args constructor.
   * @param specCode Код характеристики
   * @param specName Наименование характеристики
   * @param specTypeCode Тип данных (1-строка, 2-число, 3-дата)
   * @param specTypeName Наименование типа данных
   * @param specValue Значение характеристики
   * @param specFormat Формат передачи характеристики
   * @param specMeasure Единица измерения
   * @param norms The new value for norms
   * @param mismatch Результаты проверки параметра 0 - не соответствует 1 - соответствует 2 - аттестация не требуется, справочное значение 3 - нет результатов испытаний, но аттестация требуется 4 - не соответствует, но есть рекомендации по устранению не соответствия 5 - соответствует, изменено сотрудником УАИП
   * @param note Пояснение результата проверки характеристики
   * @param defectSuggestion Текст рекомендации по устранению 'не соответствия'
   */
  public RecordMettallographicSpecifications(java.lang.Integer specCode, java.lang.CharSequence specName, java.lang.Integer specTypeCode, java.lang.CharSequence specTypeName, java.lang.Object specValue, java.lang.CharSequence specFormat, java.lang.CharSequence specMeasure, nlmk.l3.apcs.NormMetallData norms, java.lang.Integer mismatch, java.lang.CharSequence note, java.lang.CharSequence defectSuggestion) {
    this.specCode = specCode;
    this.specName = specName;
    this.specTypeCode = specTypeCode;
    this.specTypeName = specTypeName;
    this.specValue = specValue;
    this.specFormat = specFormat;
    this.specMeasure = specMeasure;
    this.norms = norms;
    this.mismatch = mismatch;
    this.note = note;
    this.defectSuggestion = defectSuggestion;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return specCode;
    case 1: return specName;
    case 2: return specTypeCode;
    case 3: return specTypeName;
    case 4: return specValue;
    case 5: return specFormat;
    case 6: return specMeasure;
    case 7: return norms;
    case 8: return mismatch;
    case 9: return note;
    case 10: return defectSuggestion;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: specCode = (java.lang.Integer)value$; break;
    case 1: specName = (java.lang.CharSequence)value$; break;
    case 2: specTypeCode = (java.lang.Integer)value$; break;
    case 3: specTypeName = (java.lang.CharSequence)value$; break;
    case 4: specValue = value$; break;
    case 5: specFormat = (java.lang.CharSequence)value$; break;
    case 6: specMeasure = (java.lang.CharSequence)value$; break;
    case 7: norms = (nlmk.l3.apcs.NormMetallData)value$; break;
    case 8: mismatch = (java.lang.Integer)value$; break;
    case 9: note = (java.lang.CharSequence)value$; break;
    case 10: defectSuggestion = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'specCode' field.
   * @return Код характеристики
   */
  public int getSpecCode() {
    return specCode;
  }


  /**
   * Sets the value of the 'specCode' field.
   * Код характеристики
   * @param value the value to set.
   */
  public void setSpecCode(int value) {
    this.specCode = value;
  }

  /**
   * Gets the value of the 'specName' field.
   * @return Наименование характеристики
   */
  public java.lang.CharSequence getSpecName() {
    return specName;
  }


  /**
   * Sets the value of the 'specName' field.
   * Наименование характеристики
   * @param value the value to set.
   */
  public void setSpecName(java.lang.CharSequence value) {
    this.specName = value;
  }

  /**
   * Gets the value of the 'specTypeCode' field.
   * @return Тип данных (1-строка, 2-число, 3-дата)
   */
  public int getSpecTypeCode() {
    return specTypeCode;
  }


  /**
   * Sets the value of the 'specTypeCode' field.
   * Тип данных (1-строка, 2-число, 3-дата)
   * @param value the value to set.
   */
  public void setSpecTypeCode(int value) {
    this.specTypeCode = value;
  }

  /**
   * Gets the value of the 'specTypeName' field.
   * @return Наименование типа данных
   */
  public java.lang.CharSequence getSpecTypeName() {
    return specTypeName;
  }


  /**
   * Sets the value of the 'specTypeName' field.
   * Наименование типа данных
   * @param value the value to set.
   */
  public void setSpecTypeName(java.lang.CharSequence value) {
    this.specTypeName = value;
  }

  /**
   * Gets the value of the 'specValue' field.
   * @return Значение характеристики
   */
  public java.lang.Object getSpecValue() {
    return specValue;
  }


  /**
   * Sets the value of the 'specValue' field.
   * Значение характеристики
   * @param value the value to set.
   */
  public void setSpecValue(java.lang.Object value) {
    this.specValue = value;
  }

  /**
   * Gets the value of the 'specFormat' field.
   * @return Формат передачи характеристики
   */
  public java.lang.CharSequence getSpecFormat() {
    return specFormat;
  }


  /**
   * Sets the value of the 'specFormat' field.
   * Формат передачи характеристики
   * @param value the value to set.
   */
  public void setSpecFormat(java.lang.CharSequence value) {
    this.specFormat = value;
  }

  /**
   * Gets the value of the 'specMeasure' field.
   * @return Единица измерения
   */
  public java.lang.CharSequence getSpecMeasure() {
    return specMeasure;
  }


  /**
   * Sets the value of the 'specMeasure' field.
   * Единица измерения
   * @param value the value to set.
   */
  public void setSpecMeasure(java.lang.CharSequence value) {
    this.specMeasure = value;
  }

  /**
   * Gets the value of the 'norms' field.
   * @return The value of the 'norms' field.
   */
  public nlmk.l3.apcs.NormMetallData getNorms() {
    return norms;
  }


  /**
   * Sets the value of the 'norms' field.
   * @param value the value to set.
   */
  public void setNorms(nlmk.l3.apcs.NormMetallData value) {
    this.norms = value;
  }

  /**
   * Gets the value of the 'mismatch' field.
   * @return Результаты проверки параметра 0 - не соответствует 1 - соответствует 2 - аттестация не требуется, справочное значение 3 - нет результатов испытаний, но аттестация требуется 4 - не соответствует, но есть рекомендации по устранению не соответствия 5 - соответствует, изменено сотрудником УАИП
   */
  public int getMismatch() {
    return mismatch;
  }


  /**
   * Sets the value of the 'mismatch' field.
   * Результаты проверки параметра 0 - не соответствует 1 - соответствует 2 - аттестация не требуется, справочное значение 3 - нет результатов испытаний, но аттестация требуется 4 - не соответствует, но есть рекомендации по устранению не соответствия 5 - соответствует, изменено сотрудником УАИП
   * @param value the value to set.
   */
  public void setMismatch(int value) {
    this.mismatch = value;
  }

  /**
   * Gets the value of the 'note' field.
   * @return Пояснение результата проверки характеристики
   */
  public java.lang.CharSequence getNote() {
    return note;
  }


  /**
   * Sets the value of the 'note' field.
   * Пояснение результата проверки характеристики
   * @param value the value to set.
   */
  public void setNote(java.lang.CharSequence value) {
    this.note = value;
  }

  /**
   * Gets the value of the 'defectSuggestion' field.
   * @return Текст рекомендации по устранению 'не соответствия'
   */
  public java.lang.CharSequence getDefectSuggestion() {
    return defectSuggestion;
  }


  /**
   * Sets the value of the 'defectSuggestion' field.
   * Текст рекомендации по устранению 'не соответствия'
   * @param value the value to set.
   */
  public void setDefectSuggestion(java.lang.CharSequence value) {
    this.defectSuggestion = value;
  }

  /**
   * Creates a new RecordMettallographicSpecifications RecordBuilder.
   * @return A new RecordMettallographicSpecifications RecordBuilder
   */
  public static nlmk.l3.apcs.RecordMettallographicSpecifications.Builder newBuilder() {
    return new nlmk.l3.apcs.RecordMettallographicSpecifications.Builder();
  }

  /**
   * Creates a new RecordMettallographicSpecifications RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new RecordMettallographicSpecifications RecordBuilder
   */
  public static nlmk.l3.apcs.RecordMettallographicSpecifications.Builder newBuilder(nlmk.l3.apcs.RecordMettallographicSpecifications.Builder other) {
    if (other == null) {
      return new nlmk.l3.apcs.RecordMettallographicSpecifications.Builder();
    } else {
      return new nlmk.l3.apcs.RecordMettallographicSpecifications.Builder(other);
    }
  }

  /**
   * Creates a new RecordMettallographicSpecifications RecordBuilder by copying an existing RecordMettallographicSpecifications instance.
   * @param other The existing instance to copy.
   * @return A new RecordMettallographicSpecifications RecordBuilder
   */
  public static nlmk.l3.apcs.RecordMettallographicSpecifications.Builder newBuilder(nlmk.l3.apcs.RecordMettallographicSpecifications other) {
    if (other == null) {
      return new nlmk.l3.apcs.RecordMettallographicSpecifications.Builder();
    } else {
      return new nlmk.l3.apcs.RecordMettallographicSpecifications.Builder(other);
    }
  }

  /**
   * RecordBuilder for RecordMettallographicSpecifications instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<RecordMettallographicSpecifications>
    implements org.apache.avro.data.RecordBuilder<RecordMettallographicSpecifications> {

    /** Код характеристики */
    private int specCode;
    /** Наименование характеристики */
    private java.lang.CharSequence specName;
    /** Тип данных (1-строка, 2-число, 3-дата) */
    private int specTypeCode;
    /** Наименование типа данных */
    private java.lang.CharSequence specTypeName;
    /** Значение характеристики */
    private java.lang.Object specValue;
    /** Формат передачи характеристики */
    private java.lang.CharSequence specFormat;
    /** Единица измерения */
    private java.lang.CharSequence specMeasure;
    private nlmk.l3.apcs.NormMetallData norms;
    private nlmk.l3.apcs.NormMetallData.Builder normsBuilder;
    /** Результаты проверки параметра 0 - не соответствует 1 - соответствует 2 - аттестация не требуется, справочное значение 3 - нет результатов испытаний, но аттестация требуется 4 - не соответствует, но есть рекомендации по устранению не соответствия 5 - соответствует, изменено сотрудником УАИП */
    private int mismatch;
    /** Пояснение результата проверки характеристики */
    private java.lang.CharSequence note;
    /** Текст рекомендации по устранению 'не соответствия' */
    private java.lang.CharSequence defectSuggestion;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(nlmk.l3.apcs.RecordMettallographicSpecifications.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.specCode)) {
        this.specCode = data().deepCopy(fields()[0].schema(), other.specCode);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.specName)) {
        this.specName = data().deepCopy(fields()[1].schema(), other.specName);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.specTypeCode)) {
        this.specTypeCode = data().deepCopy(fields()[2].schema(), other.specTypeCode);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.specTypeName)) {
        this.specTypeName = data().deepCopy(fields()[3].schema(), other.specTypeName);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.specValue)) {
        this.specValue = data().deepCopy(fields()[4].schema(), other.specValue);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.specFormat)) {
        this.specFormat = data().deepCopy(fields()[5].schema(), other.specFormat);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.specMeasure)) {
        this.specMeasure = data().deepCopy(fields()[6].schema(), other.specMeasure);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (isValidValue(fields()[7], other.norms)) {
        this.norms = data().deepCopy(fields()[7].schema(), other.norms);
        fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
      if (other.hasNormsBuilder()) {
        this.normsBuilder = nlmk.l3.apcs.NormMetallData.newBuilder(other.getNormsBuilder());
      }
      if (isValidValue(fields()[8], other.mismatch)) {
        this.mismatch = data().deepCopy(fields()[8].schema(), other.mismatch);
        fieldSetFlags()[8] = other.fieldSetFlags()[8];
      }
      if (isValidValue(fields()[9], other.note)) {
        this.note = data().deepCopy(fields()[9].schema(), other.note);
        fieldSetFlags()[9] = other.fieldSetFlags()[9];
      }
      if (isValidValue(fields()[10], other.defectSuggestion)) {
        this.defectSuggestion = data().deepCopy(fields()[10].schema(), other.defectSuggestion);
        fieldSetFlags()[10] = other.fieldSetFlags()[10];
      }
    }

    /**
     * Creates a Builder by copying an existing RecordMettallographicSpecifications instance
     * @param other The existing instance to copy.
     */
    private Builder(nlmk.l3.apcs.RecordMettallographicSpecifications other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.specCode)) {
        this.specCode = data().deepCopy(fields()[0].schema(), other.specCode);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.specName)) {
        this.specName = data().deepCopy(fields()[1].schema(), other.specName);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.specTypeCode)) {
        this.specTypeCode = data().deepCopy(fields()[2].schema(), other.specTypeCode);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.specTypeName)) {
        this.specTypeName = data().deepCopy(fields()[3].schema(), other.specTypeName);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.specValue)) {
        this.specValue = data().deepCopy(fields()[4].schema(), other.specValue);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.specFormat)) {
        this.specFormat = data().deepCopy(fields()[5].schema(), other.specFormat);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.specMeasure)) {
        this.specMeasure = data().deepCopy(fields()[6].schema(), other.specMeasure);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.norms)) {
        this.norms = data().deepCopy(fields()[7].schema(), other.norms);
        fieldSetFlags()[7] = true;
      }
      this.normsBuilder = null;
      if (isValidValue(fields()[8], other.mismatch)) {
        this.mismatch = data().deepCopy(fields()[8].schema(), other.mismatch);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.note)) {
        this.note = data().deepCopy(fields()[9].schema(), other.note);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.defectSuggestion)) {
        this.defectSuggestion = data().deepCopy(fields()[10].schema(), other.defectSuggestion);
        fieldSetFlags()[10] = true;
      }
    }

    /**
      * Gets the value of the 'specCode' field.
      * Код характеристики
      * @return The value.
      */
    public int getSpecCode() {
      return specCode;
    }


    /**
      * Sets the value of the 'specCode' field.
      * Код характеристики
      * @param value The value of 'specCode'.
      * @return This builder.
      */
    public nlmk.l3.apcs.RecordMettallographicSpecifications.Builder setSpecCode(int value) {
      validate(fields()[0], value);
      this.specCode = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'specCode' field has been set.
      * Код характеристики
      * @return True if the 'specCode' field has been set, false otherwise.
      */
    public boolean hasSpecCode() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'specCode' field.
      * Код характеристики
      * @return This builder.
      */
    public nlmk.l3.apcs.RecordMettallographicSpecifications.Builder clearSpecCode() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'specName' field.
      * Наименование характеристики
      * @return The value.
      */
    public java.lang.CharSequence getSpecName() {
      return specName;
    }


    /**
      * Sets the value of the 'specName' field.
      * Наименование характеристики
      * @param value The value of 'specName'.
      * @return This builder.
      */
    public nlmk.l3.apcs.RecordMettallographicSpecifications.Builder setSpecName(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.specName = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'specName' field has been set.
      * Наименование характеристики
      * @return True if the 'specName' field has been set, false otherwise.
      */
    public boolean hasSpecName() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'specName' field.
      * Наименование характеристики
      * @return This builder.
      */
    public nlmk.l3.apcs.RecordMettallographicSpecifications.Builder clearSpecName() {
      specName = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'specTypeCode' field.
      * Тип данных (1-строка, 2-число, 3-дата)
      * @return The value.
      */
    public int getSpecTypeCode() {
      return specTypeCode;
    }


    /**
      * Sets the value of the 'specTypeCode' field.
      * Тип данных (1-строка, 2-число, 3-дата)
      * @param value The value of 'specTypeCode'.
      * @return This builder.
      */
    public nlmk.l3.apcs.RecordMettallographicSpecifications.Builder setSpecTypeCode(int value) {
      validate(fields()[2], value);
      this.specTypeCode = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'specTypeCode' field has been set.
      * Тип данных (1-строка, 2-число, 3-дата)
      * @return True if the 'specTypeCode' field has been set, false otherwise.
      */
    public boolean hasSpecTypeCode() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'specTypeCode' field.
      * Тип данных (1-строка, 2-число, 3-дата)
      * @return This builder.
      */
    public nlmk.l3.apcs.RecordMettallographicSpecifications.Builder clearSpecTypeCode() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'specTypeName' field.
      * Наименование типа данных
      * @return The value.
      */
    public java.lang.CharSequence getSpecTypeName() {
      return specTypeName;
    }


    /**
      * Sets the value of the 'specTypeName' field.
      * Наименование типа данных
      * @param value The value of 'specTypeName'.
      * @return This builder.
      */
    public nlmk.l3.apcs.RecordMettallographicSpecifications.Builder setSpecTypeName(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.specTypeName = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'specTypeName' field has been set.
      * Наименование типа данных
      * @return True if the 'specTypeName' field has been set, false otherwise.
      */
    public boolean hasSpecTypeName() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'specTypeName' field.
      * Наименование типа данных
      * @return This builder.
      */
    public nlmk.l3.apcs.RecordMettallographicSpecifications.Builder clearSpecTypeName() {
      specTypeName = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'specValue' field.
      * Значение характеристики
      * @return The value.
      */
    public java.lang.Object getSpecValue() {
      return specValue;
    }


    /**
      * Sets the value of the 'specValue' field.
      * Значение характеристики
      * @param value The value of 'specValue'.
      * @return This builder.
      */
    public nlmk.l3.apcs.RecordMettallographicSpecifications.Builder setSpecValue(java.lang.Object value) {
      validate(fields()[4], value);
      this.specValue = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'specValue' field has been set.
      * Значение характеристики
      * @return True if the 'specValue' field has been set, false otherwise.
      */
    public boolean hasSpecValue() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'specValue' field.
      * Значение характеристики
      * @return This builder.
      */
    public nlmk.l3.apcs.RecordMettallographicSpecifications.Builder clearSpecValue() {
      specValue = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'specFormat' field.
      * Формат передачи характеристики
      * @return The value.
      */
    public java.lang.CharSequence getSpecFormat() {
      return specFormat;
    }


    /**
      * Sets the value of the 'specFormat' field.
      * Формат передачи характеристики
      * @param value The value of 'specFormat'.
      * @return This builder.
      */
    public nlmk.l3.apcs.RecordMettallographicSpecifications.Builder setSpecFormat(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.specFormat = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'specFormat' field has been set.
      * Формат передачи характеристики
      * @return True if the 'specFormat' field has been set, false otherwise.
      */
    public boolean hasSpecFormat() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'specFormat' field.
      * Формат передачи характеристики
      * @return This builder.
      */
    public nlmk.l3.apcs.RecordMettallographicSpecifications.Builder clearSpecFormat() {
      specFormat = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'specMeasure' field.
      * Единица измерения
      * @return The value.
      */
    public java.lang.CharSequence getSpecMeasure() {
      return specMeasure;
    }


    /**
      * Sets the value of the 'specMeasure' field.
      * Единица измерения
      * @param value The value of 'specMeasure'.
      * @return This builder.
      */
    public nlmk.l3.apcs.RecordMettallographicSpecifications.Builder setSpecMeasure(java.lang.CharSequence value) {
      validate(fields()[6], value);
      this.specMeasure = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'specMeasure' field has been set.
      * Единица измерения
      * @return True if the 'specMeasure' field has been set, false otherwise.
      */
    public boolean hasSpecMeasure() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'specMeasure' field.
      * Единица измерения
      * @return This builder.
      */
    public nlmk.l3.apcs.RecordMettallographicSpecifications.Builder clearSpecMeasure() {
      specMeasure = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'norms' field.
      * @return The value.
      */
    public nlmk.l3.apcs.NormMetallData getNorms() {
      return norms;
    }


    /**
      * Sets the value of the 'norms' field.
      * @param value The value of 'norms'.
      * @return This builder.
      */
    public nlmk.l3.apcs.RecordMettallographicSpecifications.Builder setNorms(nlmk.l3.apcs.NormMetallData value) {
      validate(fields()[7], value);
      this.normsBuilder = null;
      this.norms = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'norms' field has been set.
      * @return True if the 'norms' field has been set, false otherwise.
      */
    public boolean hasNorms() {
      return fieldSetFlags()[7];
    }

    /**
     * Gets the Builder instance for the 'norms' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public nlmk.l3.apcs.NormMetallData.Builder getNormsBuilder() {
      if (normsBuilder == null) {
        if (hasNorms()) {
          setNormsBuilder(nlmk.l3.apcs.NormMetallData.newBuilder(norms));
        } else {
          setNormsBuilder(nlmk.l3.apcs.NormMetallData.newBuilder());
        }
      }
      return normsBuilder;
    }

    /**
     * Sets the Builder instance for the 'norms' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */

    public nlmk.l3.apcs.RecordMettallographicSpecifications.Builder setNormsBuilder(nlmk.l3.apcs.NormMetallData.Builder value) {
      clearNorms();
      normsBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'norms' field has an active Builder instance
     * @return True if the 'norms' field has an active Builder instance
     */
    public boolean hasNormsBuilder() {
      return normsBuilder != null;
    }

    /**
      * Clears the value of the 'norms' field.
      * @return This builder.
      */
    public nlmk.l3.apcs.RecordMettallographicSpecifications.Builder clearNorms() {
      norms = null;
      normsBuilder = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'mismatch' field.
      * Результаты проверки параметра 0 - не соответствует 1 - соответствует 2 - аттестация не требуется, справочное значение 3 - нет результатов испытаний, но аттестация требуется 4 - не соответствует, но есть рекомендации по устранению не соответствия 5 - соответствует, изменено сотрудником УАИП
      * @return The value.
      */
    public int getMismatch() {
      return mismatch;
    }


    /**
      * Sets the value of the 'mismatch' field.
      * Результаты проверки параметра 0 - не соответствует 1 - соответствует 2 - аттестация не требуется, справочное значение 3 - нет результатов испытаний, но аттестация требуется 4 - не соответствует, но есть рекомендации по устранению не соответствия 5 - соответствует, изменено сотрудником УАИП
      * @param value The value of 'mismatch'.
      * @return This builder.
      */
    public nlmk.l3.apcs.RecordMettallographicSpecifications.Builder setMismatch(int value) {
      validate(fields()[8], value);
      this.mismatch = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'mismatch' field has been set.
      * Результаты проверки параметра 0 - не соответствует 1 - соответствует 2 - аттестация не требуется, справочное значение 3 - нет результатов испытаний, но аттестация требуется 4 - не соответствует, но есть рекомендации по устранению не соответствия 5 - соответствует, изменено сотрудником УАИП
      * @return True if the 'mismatch' field has been set, false otherwise.
      */
    public boolean hasMismatch() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'mismatch' field.
      * Результаты проверки параметра 0 - не соответствует 1 - соответствует 2 - аттестация не требуется, справочное значение 3 - нет результатов испытаний, но аттестация требуется 4 - не соответствует, но есть рекомендации по устранению не соответствия 5 - соответствует, изменено сотрудником УАИП
      * @return This builder.
      */
    public nlmk.l3.apcs.RecordMettallographicSpecifications.Builder clearMismatch() {
      fieldSetFlags()[8] = false;
      return this;
    }

    /**
      * Gets the value of the 'note' field.
      * Пояснение результата проверки характеристики
      * @return The value.
      */
    public java.lang.CharSequence getNote() {
      return note;
    }


    /**
      * Sets the value of the 'note' field.
      * Пояснение результата проверки характеристики
      * @param value The value of 'note'.
      * @return This builder.
      */
    public nlmk.l3.apcs.RecordMettallographicSpecifications.Builder setNote(java.lang.CharSequence value) {
      validate(fields()[9], value);
      this.note = value;
      fieldSetFlags()[9] = true;
      return this;
    }

    /**
      * Checks whether the 'note' field has been set.
      * Пояснение результата проверки характеристики
      * @return True if the 'note' field has been set, false otherwise.
      */
    public boolean hasNote() {
      return fieldSetFlags()[9];
    }


    /**
      * Clears the value of the 'note' field.
      * Пояснение результата проверки характеристики
      * @return This builder.
      */
    public nlmk.l3.apcs.RecordMettallographicSpecifications.Builder clearNote() {
      note = null;
      fieldSetFlags()[9] = false;
      return this;
    }

    /**
      * Gets the value of the 'defectSuggestion' field.
      * Текст рекомендации по устранению 'не соответствия'
      * @return The value.
      */
    public java.lang.CharSequence getDefectSuggestion() {
      return defectSuggestion;
    }


    /**
      * Sets the value of the 'defectSuggestion' field.
      * Текст рекомендации по устранению 'не соответствия'
      * @param value The value of 'defectSuggestion'.
      * @return This builder.
      */
    public nlmk.l3.apcs.RecordMettallographicSpecifications.Builder setDefectSuggestion(java.lang.CharSequence value) {
      validate(fields()[10], value);
      this.defectSuggestion = value;
      fieldSetFlags()[10] = true;
      return this;
    }

    /**
      * Checks whether the 'defectSuggestion' field has been set.
      * Текст рекомендации по устранению 'не соответствия'
      * @return True if the 'defectSuggestion' field has been set, false otherwise.
      */
    public boolean hasDefectSuggestion() {
      return fieldSetFlags()[10];
    }


    /**
      * Clears the value of the 'defectSuggestion' field.
      * Текст рекомендации по устранению 'не соответствия'
      * @return This builder.
      */
    public nlmk.l3.apcs.RecordMettallographicSpecifications.Builder clearDefectSuggestion() {
      defectSuggestion = null;
      fieldSetFlags()[10] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public RecordMettallographicSpecifications build() {
      try {
        RecordMettallographicSpecifications record = new RecordMettallographicSpecifications();
        record.specCode = fieldSetFlags()[0] ? this.specCode : (java.lang.Integer) defaultValue(fields()[0]);
        record.specName = fieldSetFlags()[1] ? this.specName : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.specTypeCode = fieldSetFlags()[2] ? this.specTypeCode : (java.lang.Integer) defaultValue(fields()[2]);
        record.specTypeName = fieldSetFlags()[3] ? this.specTypeName : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.specValue = fieldSetFlags()[4] ? this.specValue :  defaultValue(fields()[4]);
        record.specFormat = fieldSetFlags()[5] ? this.specFormat : (java.lang.CharSequence) defaultValue(fields()[5]);
        record.specMeasure = fieldSetFlags()[6] ? this.specMeasure : (java.lang.CharSequence) defaultValue(fields()[6]);
        if (normsBuilder != null) {
          try {
            record.norms = this.normsBuilder.build();
          } catch (org.apache.avro.AvroMissingFieldException e) {
            e.addParentField(record.getSchema().getField("norms"));
            throw e;
          }
        } else {
          record.norms = fieldSetFlags()[7] ? this.norms : (nlmk.l3.apcs.NormMetallData) defaultValue(fields()[7]);
        }
        record.mismatch = fieldSetFlags()[8] ? this.mismatch : (java.lang.Integer) defaultValue(fields()[8]);
        record.note = fieldSetFlags()[9] ? this.note : (java.lang.CharSequence) defaultValue(fields()[9]);
        record.defectSuggestion = fieldSetFlags()[10] ? this.defectSuggestion : (java.lang.CharSequence) defaultValue(fields()[10]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<RecordMettallographicSpecifications>
    WRITER$ = (org.apache.avro.io.DatumWriter<RecordMettallographicSpecifications>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<RecordMettallographicSpecifications>
    READER$ = (org.apache.avro.io.DatumReader<RecordMettallographicSpecifications>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










